import { db } from "./db";
import { hospitals } from "@shared/schema";
import { count } from "drizzle-orm";

const lagosHospitals = [
  {
    name: "Lagos University Teaching Hospital (LUTH)",
    address: "Ishaga Rd, Idi-Araba, Lagos",
    lga: "Mushin",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Oncology", "Dentistry", "Pediatrics", "Surgery", "Emergency", "Radiology"],
    email: "info@luth.gov.ng",
    latitude: 6.5244,
    longitude: 3.3556,
  },
  {
    name: "Lagos State University Teaching Hospital (LASUTH)",
    address: "1-5 Oba Akinjobi Way, Ikeja, Lagos",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Critical Care", "Surgery", "Pediatrics", "Internal Medicine", "Trauma"],
    email: "enquiry@lasuth.org.ng",
    latitude: 6.5956,
    longitude: 3.3421,
  },
  {
    name: "Reddington Hospital",
    address: "12 Idowu Martins St, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 132,
    operatingHours: "24/7",
    services: ["Cardiology", "Gastroenterology", "Nephrology", "Surgery", "Maternity"],
    email: "info@reddingtonhospital.com",
    latitude: 6.4285,
    longitude: 3.4225,
  },
  {
    name: "Lagoon Hospitals (Victoria Island)",
    address: "17B Bishop Aboyade Cole St, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 50,
    operatingHours: "24/7",
    services: ["Orthopedics", "Trauma", "Surgery", "General Medicine"],
    latitude: 6.4281,
    longitude: 3.4219,
  },
  {
    name: "St. Nicholas Hospital",
    address: "57 Campbell St, Lagos Island, Lagos",
    lga: "Lagos Island",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 50,
    operatingHours: "24/7",
    services: ["Nephrology", "Kidney Transplant", "Oncology", "Dialysis"],
    latitude: 6.4531,
    longitude: 3.3958,
  },
  {
    name: "Gbagada General Hospital",
    address: "1 Hospital Rd, Araromi, Gbagada, Lagos",
    lga: "Kosofe",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Dialysis", "Cardiology", "Emergency"],
    latitude: 6.5569,
    longitude: 3.3914,
  },
  {
    name: "National Orthopaedic Hospital, Igbobi",
    address: "Ikorodu Road, Igbobi, Lagos",
    lga: "Somolu",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 450,
    operatingHours: "24/7",
    services: ["Orthopedics", "Trauma Surgery", "Physiotherapy", "Prosthetics"],
    latitude: 6.5333,
    longitude: 3.3667,
  },
  {
    name: "Federal Medical Centre, Ebute Metta",
    address: "Railway Compound, Ebute-Metta, Lagos",
    lga: "Lagos Mainland",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Surgery", "Internal Medicine", "Pediatrics", "Obstetrics"],
    latitude: 6.4886,
    longitude: 3.3792,
  },
  {
    name: "Eko Hospital",
    address: "Mobolaji Bank Anthony Way, Ikeja, Lagos",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 130,
    operatingHours: "24/7",
    services: ["Radiotherapy", "General Medicine", "Surgery"],
    latitude: 6.5774,
    longitude: 3.3662,
  },
  {
    name: "First Consultants Medical Centre",
    address: "St. Gregory's College Road, Obalende, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 40,
    operatingHours: "24/7",
    services: ["General Practice", "Infectious Diseases", "Gynecology"],
    latitude: 6.4453,
    longitude: 3.4112,
  },
  {
    name: "Evercare Hospital Lekki",
    address: "Bisola Durosinmi Etti Dr, Lekki Phase 1, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 165,
    operatingHours: "24/7",
    services: ["Cardiology", "Neurology", "Orthopedics", "Critical Care"],
    latitude: 6.4474,
    longitude: 3.4731,
  },
  {
    name: "St. Ives Hospital",
    address: "12 Salvation Road, Opebi, Ikeja",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 45,
    operatingHours: "24/7",
    services: ["IVF", "Gynecology", "Obstetrics"],
    latitude: 6.5938,
    longitude: 3.3576,
  },
  {
    name: "Paelon Memorial Hospital",
    address: "1221 Ahmadu Bello Way, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 25,
    operatingHours: "24/7",
    services: ["Family Medicine", "Pediatrics", "Corporate Health"],
    latitude: 6.4253,
    longitude: 3.4211,
  },
  {
    name: "Nordica Fertility Centre",
    address: "106/108 Norman Williams Street, Ikoyi, Lagos",
    lga: "Ikoyi",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 15,
    operatingHours: "8am - 5pm",
    services: ["IVF", "Egg Freezing", "Andrology"],
    latitude: 6.4442,
    longitude: 3.4185,
  },
  {
    name: "Lagos Island General Hospital (Odan)",
    address: "1-3 Broad Street, Odan, Lagos",
    lga: "Lagos Island",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 250,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity", "Eye Clinic"],
    latitude: 6.4539,
    longitude: 3.3903,
  },
  {
    name: "General Hospital, Ikeja",
    address: "349b Odusami Street, off Wemco Rd, Ogba, Ikeja",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 180,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics"],
    latitude: 6.6219,
    longitude: 3.3461,
  },
  {
    name: "General Hospital, Ikorodu",
    address: "TOS Benson Road, Ebute, Ikorodu",
    lga: "Ikorodu",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 6.6083,
    longitude: 3.4917,
  },
  {
    name: "General Hospital, Badagry",
    address: "Badagry, Lagos",
    lga: "Badagry",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity"],
    latitude: 6.4167,
    longitude: 2.8833,
  },
  {
    name: "General Hospital, Epe",
    address: "Epe, Lagos",
    lga: "Epe",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 120,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity"],
    latitude: 6.5833,
    longitude: 3.9833,
  },
  {
    name: "Alimosho General Hospital",
    address: "Lasu-Isheri Rd, Igando, Lagos",
    lga: "Alimosho",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Pediatrics"],
    latitude: 6.5592,
    longitude: 3.2503,
  },
  {
    name: "Duchess International Hospital",
    address: "22A Joel Ogunnaike St, Ikeja GRA, Lagos",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 72,
    operatingHours: "24/7",
    services: ["Cardiology", "Surgery", "Wellness"],
    latitude: 6.5818,
    longitude: 3.3562,
  },
  {
    name: "Kelina Hospital",
    address: "7 Ologun Agbaje St, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 30,
    operatingHours: "24/7",
    services: ["Laser Surgery", "Urology", "Lithotripsy"],
    latitude: 6.4298,
    longitude: 3.4143,
  },
  {
    name: "The Bridge Clinic",
    address: "66 Oduduwa Way, Ikeja GRA, Lagos",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 10,
    operatingHours: "8am - 5pm",
    services: ["IVF", "Fertility Treatment"],
    latitude: 6.5764,
    longitude: 3.3567,
  },
  {
    name: "Eye Foundation Hospital",
    address: "50 Ogunlana Drive, Surulere, Lagos",
    lga: "Surulere",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 20,
    operatingHours: "24/7",
    services: ["Ophthalmology", "Eye Surgery", "Optometry"],
    latitude: 6.4938,
    longitude: 3.3558,
  },
  {
    name: "Lifebridge Specialist Hospital",
    address: "42 Montgomery Road, Sabo Yaba, Lagos",
    lga: "Yaba",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 35,
    operatingHours: "24/7",
    services: ["Cardiology", "Orthopedics", "General Surgery"],
    latitude: 6.5074,
    longitude: 3.3745,
  },
  {
    name: "National Hospital Abuja",
    address: "Plot 132, Central District, Abuja",
    lga: "Municipal Area Council",
    state: "FCT",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Cardiology", "Oncology", "Neurology"],
    email: "info@nationalhospitalabuja.net",
    website: "https://www.nationalhospitalabuja.net",
    phone: "+234 9 5238771",
    latitude: 9.0579,
    longitude: 7.4951,
  },
  {
    name: "University of Abuja Teaching Hospital (UATH)",
    address: "Gwagwalada, Abuja",
    lga: "Gwagwalada",
    state: "FCT",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics", "Obstetrics"],
    email: "info@uath.gov.ng",
    website: "https://uath.gov.ng",
    phone: "+234 8 0800282",
    latitude: 8.9472,
    longitude: 7.0903,
  },
  {
    name: "Cedarcrest Hospitals",
    address: "2 Sam Mbakwe Street, Gudu District, Apo, Abuja",
    lga: "Municipal Area Council",
    state: "FCT",
    ownership: "Private",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Cancer Treatment", "Surgery", "Cardiology"],
    website: "https://cedarcresthospitals.com",
    latitude: 9.0127,
    longitude: 7.5069,
  },
  {
    name: "Nisa Premier Hospital",
    address: "Plot 1843 Life Camp, Abuja",
    lga: "Bwari",
    state: "FCT",
    ownership: "Private",
    bedCapacity: 80,
    operatingHours: "24/7",
    services: ["Robotic Surgery", "Fertility", "Cardiology", "General Surgery"],
    website: "https://nisa.com.ng",
    latitude: 9.0820,
    longitude: 7.4028,
  },
  {
    name: "Aminu Kano Teaching Hospital",
    address: "Zaria Road, Kano",
    lga: "Tarauni",
    state: "Kano",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Neurology", "Surgery"],
    website: "https://akth.org.ng",
    latitude: 11.9646,
    longitude: 8.4989,
  },
  {
    name: "University of Benin Teaching Hospital (UBTH)",
    address: "PMB 1111, Benin City, Edo State",
    lga: "Egor",
    state: "Edo",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Neurology"],
    website: "https://ubth.org",
    latitude: 6.3244,
    longitude: 5.6089,
  },
  {
    name: "Obafemi Awolowo University Teaching Hospital (OAUTH)",
    address: "Ile-Ife, Osun State",
    lga: "Ife Central",
    state: "Osun",
    ownership: "Government",
    bedCapacity: 600,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 7.5176,
    longitude: 4.5230,
  },
  {
    name: "University College Hospital (UCH)",
    address: "Queen Elizabeth Road, Ibadan",
    lga: "Ibadan North",
    state: "Oyo",
    ownership: "Government",
    bedCapacity: 900,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Neurology", "Surgery"],
    website: "https://uch-ibadan.org.ng",
    latitude: 7.4009,
    longitude: 3.9028,
  },
  {
    name: "Jos University Teaching Hospital (JUTH)",
    address: "PMB 2076, Jos, Plateau State",
    lga: "Jos North",
    state: "Plateau",
    ownership: "Government",
    bedCapacity: 700,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Neurology", "Oncology", "Surgery"],
    website: "https://juth.org.ng",
    latitude: 9.9096,
    longitude: 8.8921,
  },
  {
    name: "University of Port Harcourt Teaching Hospital (UPTH)",
    address: "East-West Road, Choba, Port Harcourt",
    lga: "Obio-Akpor",
    state: "Rivers",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Surgery", "Pediatrics", "Oncology"],
    latitude: 4.8949,
    longitude: 6.9114,
  },
  {
    name: "University of Maiduguri Teaching Hospital",
    address: "Bama Road, Maiduguri, Borno State",
    lga: "Maiduguri",
    state: "Borno",
    ownership: "Government",
    bedCapacity: 750,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Neurology"],
    website: "https://umth.edu.ng",
    latitude: 11.8333,
    longitude: 13.1500,
  },
  {
    name: "University of Calabar Teaching Hospital (UCTH)",
    address: "Calabar, Cross River State",
    lga: "Calabar Municipality",
    state: "Cross River",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 4.9580,
    longitude: 8.3261,
  },
  {
    name: "Ahmadu Bello University Teaching Hospital Zaria",
    address: "Shika, Zaria, Kaduna State",
    lga: "Zaria",
    state: "Kaduna",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Neurology", "Oncology", "Surgery"],
    website: "https://abuth.gov.ng",
    latitude: 11.1278,
    longitude: 7.6839,
  },
  {
    name: "University of Ilorin Teaching Hospital (UITH)",
    address: "Ilorin, Kwara State",
    lga: "Ilorin West",
    state: "Kwara",
    ownership: "Government",
    bedCapacity: 600,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Pediatrics"],
    website: "https://uith.org.ng",
    latitude: 8.4799,
    longitude: 4.5418,
  },
  {
    name: "Nnamdi Azikiwe University Teaching Hospital (NAUTH)",
    address: "Nnewi, Anambra State",
    lga: "Nnewi North",
    state: "Anambra",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 6.0194,
    longitude: 6.9167,
  },
  {
    name: "Enugu State University Teaching Hospital (ESUTH)",
    address: "Parklane, Enugu",
    lga: "Enugu North",
    state: "Enugu",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Obstetrics"],
    latitude: 6.4584,
    longitude: 7.5139,
  },
  {
    name: "Federal Medical Centre Owerri",
    address: "Owerri, Imo State",
    lga: "Owerri Municipal",
    state: "Imo",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 5.4836,
    longitude: 7.0333,
  },
  {
    name: "Federal Medical Centre Umuahia",
    address: "Umuahia, Abia State",
    lga: "Umuahia North",
    state: "Abia",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics"],
    latitude: 5.5261,
    longitude: 7.4942,
  },
  {
    name: "Federal Medical Centre Abeokuta",
    address: "Abeokuta, Ogun State",
    lga: "Abeokuta South",
    state: "Ogun",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 7.1556,
    longitude: 3.3486,
  },
  {
    name: "Federal Medical Centre Lokoja",
    address: "Lokoja, Kogi State",
    lga: "Lokoja",
    state: "Kogi",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    website: "https://fmclokoja.gov.ng",
    latitude: 7.8023,
    longitude: 6.7333,
  },
  {
    name: "Grandville Medical and Laser",
    address: "3 Coker Road, Ilupeju, Lagos",
    lga: "Mushin",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 25,
    operatingHours: "24/7",
    services: ["Laser Surgery", "Dermatology", "General Medicine"],
    latitude: 6.5519,
    longitude: 3.3584,
  },
  {
    name: "Rainbow Specialist Medical Centre",
    address: "29 Association Avenue, Ilupeju, Lagos",
    lga: "Mushin",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 40,
    operatingHours: "24/7",
    services: ["Pediatrics", "Gynecology", "Internal Medicine"],
    latitude: 6.5542,
    longitude: 3.3511,
  },
  {
    name: "Diamond Hospital",
    address: "8 Off Awolowo Road, Ikoyi, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 30,
    operatingHours: "24/7",
    services: ["General Surgery", "Orthopedics", "Emergency"],
    latitude: 6.4512,
    longitude: 3.4301,
  },
  {
    name: "Optimal Cancer Care Foundation",
    address: "40 Montgomery Road, Yaba, Lagos",
    lga: "Yaba",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 20,
    operatingHours: "8am - 6pm",
    services: ["Oncology", "Chemotherapy", "Radiotherapy"],
    latitude: 6.5089,
    longitude: 3.3721,
  },
];

export async function autoSeedDatabase(): Promise<void> {
  try {
    const result = await db.select({ count: count() }).from(hospitals);
    const hospitalCount = result[0]?.count || 0;
    
    console.log(`Database has ${hospitalCount} hospitals`);
    
    if (hospitalCount === 0) {
      console.log("Database is empty, auto-seeding with hospital data...");
      
      await db.insert(hospitals).values(lagosHospitals);
      
      console.log(`Auto-seeded ${lagosHospitals.length} hospitals successfully`);
    } else {
      console.log("Database already has data, skipping auto-seed");
    }
  } catch (error) {
    console.error("Auto-seed error:", error);
    throw error;
  }
}
