import { db } from "./db";
import { pharmacies, generatePharmacySlug } from "@shared/schema";
import { eq } from "drizzle-orm";

const PHARMACIES_DATA = [
  { name: "MedPlus Pharmacy Victoria Island", description: "Nigeria's leading retail pharmacy chain offering a wide range of prescription and OTC medications, health products, and wellness services.", address: "Plot 12 Adeola Odeku Street, Victoria Island", city: "Lagos", lga: "Eti-Osa", state: "Lagos", phone: "+234-1-2800100", email: "vi@medplusng.com", website: "https://medplusng.com", operatingHours: "Mon-Sat: 8AM-9PM, Sun: 10AM-6PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Health Screening", "Vaccinations", "Baby Care Products"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: true, acceptsInsurance: true, averageRating: 4.5, totalReviews: 85 },
  { name: "HealthPlus Pharmacy Ikeja", description: "Premium pharmacy offering pharmaceutical care, health consultations, and a wide selection of wellness products.", address: "3 Isaac John Street, GRA Ikeja", city: "Lagos", lga: "Ikeja", state: "Lagos", phone: "+234-1-2800200", email: "ikeja@healthplus.ng", website: "https://healthplus.com.ng", operatingHours: "Mon-Sat: 8AM-9PM, Sun: 9AM-5PM", ownership: "Private", services: ["Prescription Drugs", "Health Consultation", "Diabetes Management", "Wellness Products", "Supplements"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: true, acceptsInsurance: true, averageRating: 4.4, totalReviews: 72 },
  { name: "Alpha Pharmacy Lagos", description: "Trusted community pharmacy providing quality medications and pharmaceutical care services to Lagos residents.", address: "45 Toyin Street, Ikeja", city: "Lagos", lga: "Ikeja", state: "Lagos", phone: "+234-1-2800300", email: "info@alphapharmacy.ng", operatingHours: "24/7", ownership: "Private", services: ["24/7 Dispensing", "Prescription Drugs", "Emergency Medications", "First Aid Supplies"], isVerified: true, is24Hours: true, hasDelivery: true, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.2, totalReviews: 60 },
  { name: "Bellow's Pharmacy Surulere", description: "Family-owned pharmacy with decades of service providing affordable and quality medications in Surulere.", address: "28 Adeniran Ogunsanya Street, Surulere", city: "Lagos", lga: "Surulere", state: "Lagos", phone: "+234-1-2800400", operatingHours: "Mon-Sat: 7AM-10PM, Sun: 8AM-6PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Herbal Products", "Baby Care"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: false, averageRating: 4.0, totalReviews: 35 },
  { name: "MedPlus Pharmacy Lekki", description: "Convenient pharmacy location serving the Lekki-Ajah corridor with comprehensive pharmaceutical services.", address: "Plot 5, Admiralty Way, Lekki Phase 1", city: "Lagos", lga: "Eti-Osa", state: "Lagos", phone: "+234-1-2800500", email: "lekki@medplusng.com", website: "https://medplusng.com", operatingHours: "Mon-Sat: 8AM-9PM, Sun: 10AM-6PM", ownership: "Private", services: ["Prescription Drugs", "Beauty & Skincare", "Vitamins", "Medical Equipment", "Home Delivery"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: true, acceptsInsurance: true, averageRating: 4.3, totalReviews: 55 },
  { name: "Greenlife Pharmacy Abuja", description: "Full-service pharmacy in the heart of Abuja offering quality medications, health screenings, and wellness products.", address: "Plot 112 Aminu Kano Crescent, Wuse 2", city: "Abuja", lga: "Wuse", state: "FCT", phone: "+234-9-2900100", email: "wuse@greenlifepharmacy.ng", operatingHours: "Mon-Sat: 8AM-9PM, Sun: 10AM-5PM", ownership: "Private", services: ["Prescription Drugs", "Blood Pressure Check", "Blood Sugar Test", "Supplements", "Personal Care"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: true, acceptsInsurance: true, averageRating: 4.6, totalReviews: 90 },
  { name: "Sahad Pharmacy Garki", description: "Trusted pharmacy serving the Garki area with affordable medications and excellent customer service.", address: "Area 11, Garki", city: "Abuja", lga: "Garki", state: "FCT", phone: "+234-9-2900200", operatingHours: "Mon-Sat: 8AM-8PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Medical Supplies", "Health Advice"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.1, totalReviews: 40 },
  { name: "NISA Premier Pharmacy", description: "Hospital-based pharmacy at Nisa Premier Hospital offering a comprehensive range of medications and health products.", address: "Plot 1061, Cadastral Zone, Jabi", city: "Abuja", lga: "Jabi", state: "FCT", phone: "+234-9-2900300", email: "pharmacy@nisahospitals.com", operatingHours: "24/7", ownership: "Private", services: ["Hospital Pharmacy", "Prescription Drugs", "Specialty Medications", "Compounding Services"], isVerified: true, is24Hours: true, hasDelivery: true, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.4, totalReviews: 65 },
  { name: "Maitama Pharmacy", description: "Upscale pharmacy in Maitama district providing premium pharmaceutical services to diplomatic and residential areas.", address: "15 Nile Street, Maitama", city: "Abuja", lga: "Maitama", state: "FCT", phone: "+234-9-2900400", operatingHours: "Mon-Sat: 7AM-10PM, Sun: 9AM-6PM", ownership: "Private", services: ["Prescription Drugs", "Cosmetics", "Supplements", "Baby Products", "Medical Devices"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: true, acceptsInsurance: true, averageRating: 4.5, totalReviews: 50 },
  { name: "Drugfield Pharmacy Port Harcourt", description: "Reputable pharmacy chain providing quality medications and pharmaceutical care in the Garden City.", address: "25 Aba Road, GRA Phase 2", city: "Port Harcourt", lga: "Port Harcourt", state: "Rivers", phone: "+234-84-230100", email: "ph@drugfieldpharmacy.ng", operatingHours: "Mon-Sat: 8AM-8PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Wellness Products", "Health Screening"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.2, totalReviews: 45 },
  { name: "Vine Pharmacy PH", description: "Community pharmacy offering affordable medications and healthcare advice to Port Harcourt residents.", address: "18 Stadium Road, Port Harcourt", city: "Port Harcourt", lga: "Obio-Akpor", state: "Rivers", phone: "+234-84-230200", operatingHours: "Mon-Sat: 7AM-9PM, Sun: 8AM-4PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Herbal Remedies", "First Aid"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: false, averageRating: 3.9, totalReviews: 28 },
  { name: "GreenHill Pharmacy Kano", description: "Leading pharmacy in Kano providing quality pharmaceutical care with friendly service.", address: "10 Murtala Mohammed Way, Kano", city: "Kano", lga: "Nassarawa", state: "Kano", phone: "+234-64-310100", operatingHours: "Sat-Thu: 8AM-9PM, Fri: 2PM-9PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Traditional Medicine", "Supplements"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.0, totalReviews: 38 },
  { name: "Medicare Pharmacy Kano", description: "Trusted pharmacy serving northern Nigeria with a wide range of affordable and quality medications.", address: "12 Zoo Road, Kano", city: "Kano", lga: "Tarauni", state: "Kano", phone: "+234-64-310200", email: "info@medicarekano.ng", operatingHours: "24/7", ownership: "Private", services: ["24/7 Service", "Prescription Drugs", "Emergency Medications", "Medical Supplies", "Vaccinations"], isVerified: true, is24Hours: true, hasDelivery: true, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.3, totalReviews: 52 },
  { name: "Juhel Pharmacy Enugu", description: "Pharmaceutical retail outlet of Juhel Nigeria Limited offering quality locally manufactured and imported drugs.", address: "32 Ogui Road, Enugu", city: "Enugu", lga: "Enugu North", state: "Enugu", phone: "+234-42-250100", email: "retail@juhelng.com", operatingHours: "Mon-Sat: 8AM-8PM, Sun: 10AM-4PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Baby Care", "Wellness Products"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: true, acceptsInsurance: true, averageRating: 4.1, totalReviews: 33 },
  { name: "UBTH Pharmacy Benin City", description: "Teaching hospital pharmacy providing affordable medications and pharmaceutical care services.", address: "PMB 1111, Ugbowo, Benin City", city: "Benin City", lga: "Egor", state: "Edo", phone: "+234-52-600100", operatingHours: "Mon-Fri: 8AM-4PM, Sat: 8AM-12PM", ownership: "Government", services: ["Prescription Drugs", "Hospital Medications", "Specialty Drugs", "Patient Counseling"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 3.7, totalReviews: 22 },
  { name: "Swiss Pharma Pharmacy Ibadan", description: "Modern pharmacy offering Swiss-quality pharmaceutical care and health products in Ibadan.", address: "5 Magazine Road, Jericho, Ibadan", city: "Ibadan", lga: "Ibadan North-West", state: "Oyo", phone: "+234-2-2420100", email: "ibadan@swisspharma.ng", operatingHours: "Mon-Sat: 8AM-8PM", ownership: "Private", services: ["Prescription Drugs", "Imported Medications", "Supplements", "Skincare", "Health Consultation"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: true, acceptsInsurance: true, averageRating: 4.4, totalReviews: 48 },
  { name: "UCH Pharmacy Ibadan", description: "University College Hospital pharmacy providing affordable medications for patients and the public.", address: "Queen Elizabeth Road, Mokola, Ibadan", city: "Ibadan", lga: "Ibadan North", state: "Oyo", phone: "+234-2-2410100", operatingHours: "Mon-Fri: 8AM-6PM, Sat: 8AM-1PM", ownership: "Government", services: ["Prescription Drugs", "Affordable Medications", "Specialty Drugs", "Patient Education"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 3.8, totalReviews: 30 },
  { name: "MyDawa Pharmacy Abeokuta", description: "Reliable pharmacy providing essential medications and health products to Abeokuta residents.", address: "23 Ibara GRA, Abeokuta", city: "Abeokuta", lga: "Abeokuta South", state: "Ogun", phone: "+234-39-240100", operatingHours: "Mon-Sat: 8AM-8PM, Sun: 10AM-4PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Herbal Products", "Family Planning"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: false, averageRating: 4.0, totalReviews: 20 },
  { name: "Pharmaplus Jos", description: "Trusted pharmacy in Jos providing quality medications and health advice to Plateau State residents.", address: "8 Ahmadu Bello Way, Jos", city: "Jos", lga: "Jos North", state: "Plateau", phone: "+234-73-450100", operatingHours: "Mon-Sat: 8AM-8PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Medical Equipment", "Health Tips"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.1, totalReviews: 25 },
  { name: "Rite-Aid Pharmacy Calabar", description: "Full-service pharmacy in Calabar offering a broad range of pharmaceutical products and health services.", address: "14 Marian Road, Calabar", city: "Calabar", lga: "Calabar Municipality", state: "Cross River", phone: "+234-87-230100", operatingHours: "Mon-Sat: 8AM-8PM, Sun: 10AM-4PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Health Screening", "Wellness Products", "Baby Care"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.2, totalReviews: 32 },
  { name: "St. Nicholas Pharmacy Uyo", description: "Reliable community pharmacy serving Uyo and Akwa Ibom State with quality healthcare products.", address: "20 Oron Road, Uyo", city: "Uyo", lga: "Uyo", state: "Akwa Ibom", phone: "+234-85-200100", operatingHours: "Mon-Sat: 8AM-9PM, Sun: 9AM-5PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Cosmetics", "Supplements"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: false, averageRating: 3.9, totalReviews: 18 },
  { name: "MyPharmacy Warri", description: "Modern pharmacy in Warri offering quality pharmaceutical products and prompt customer service.", address: "15 Effurun-Sapele Road, Warri", city: "Warri", lga: "Uvwie", state: "Delta", phone: "+234-53-320100", operatingHours: "Mon-Sat: 7AM-9PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Medical Devices", "Supplements"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.0, totalReviews: 22 },
  { name: "HealthPlus Pharmacy Abuja Gwarinpa", description: "Premium HealthPlus outlet serving the Gwarinpa residential area with quality health and wellness products.", address: "Plot 254, 3rd Avenue, Gwarinpa", city: "Abuja", lga: "Gwarinpa", state: "FCT", phone: "+234-9-2900500", email: "gwarinpa@healthplus.ng", website: "https://healthplus.com.ng", operatingHours: "Mon-Sat: 8AM-9PM, Sun: 10AM-6PM", ownership: "Private", services: ["Prescription Drugs", "Wellness Products", "Health Screening", "Cosmetics", "Baby Products"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: true, acceptsInsurance: true, averageRating: 4.5, totalReviews: 58 },
  { name: "Pharmaco Pharmacy Owerri", description: "Leading pharmacy in Owerri providing comprehensive pharmaceutical care and affordable medications.", address: "10 Douglas Road, Owerri", city: "Owerri", lga: "Owerri Municipal", state: "Imo", phone: "+234-83-230100", operatingHours: "Mon-Sat: 8AM-8PM, Sun: 10AM-4PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Medical Supplies", "Health Consultation"], isVerified: true, is24Hours: false, hasDelivery: false, hasOnlineOrdering: false, acceptsInsurance: false, averageRating: 3.8, totalReviews: 15 },
  { name: "BG Pharmacy Kaduna", description: "Well-stocked pharmacy in Kaduna providing quality pharmaceutical care and health advice.", address: "22 Ahmadu Bello Way, Kaduna", city: "Kaduna", lga: "Kaduna North", state: "Kaduna", phone: "+234-62-240100", operatingHours: "Mon-Sat: 8AM-9PM", ownership: "Private", services: ["Prescription Drugs", "OTC Medications", "Vaccinations", "Health Education"], isVerified: true, is24Hours: false, hasDelivery: true, hasOnlineOrdering: false, acceptsInsurance: true, averageRating: 4.1, totalReviews: 30 },
];

export async function seedPharmacies() {
  const existing = await db.select({ id: pharmacies.id }).from(pharmacies).limit(1);
  if (existing.length > 0) {
    console.log("Pharmacies already seeded, skipping...");
    return;
  }

  console.log("Seeding pharmacies...");
  for (const data of PHARMACIES_DATA) {
    await db.insert(pharmacies).values({
      ...data,
      slug: generatePharmacySlug(data.name),
    });
  }
  console.log(`Seeded ${PHARMACIES_DATA.length} pharmacies`);
}
