import { db } from "./db";
import { hospitals } from "@shared/schema";

const nigeriaHospitals = [
  // ============================================
  // FCT (ABUJA) - Federal Capital Territory
  // ============================================
  {
    name: "National Hospital Abuja",
    address: "Plot 132, Central District, Abuja",
    lga: "Municipal Area Council",
    state: "FCT",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Cardiology", "Oncology", "Neurology"],
    email: "info@nationalhospitalabuja.net",
    website: "https://www.nationalhospitalabuja.net",
    phone: "+234 9 5238771",
    latitude: 9.0579,
    longitude: 7.4951,
  },
  {
    name: "University of Abuja Teaching Hospital (UATH)",
    address: "Gwagwalada, Abuja",
    lga: "Gwagwalada",
    state: "FCT",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics", "Obstetrics"],
    email: "info@uath.gov.ng",
    website: "https://uath.gov.ng",
    phone: "+234 8 0800282",
    latitude: 8.9472,
    longitude: 7.0903,
  },
  {
    name: "Cedarcrest Hospitals",
    address: "2 Sam Mbakwe Street, Gudu District, Apo, Abuja",
    lga: "Municipal Area Council",
    state: "FCT",
    ownership: "Private",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Cancer Treatment", "Surgery", "Cardiology"],
    website: "https://cedarcresthospitals.com",
    latitude: 9.0127,
    longitude: 7.5069,
  },
  {
    name: "Nisa Premier Hospital",
    address: "Plot 1843 Life Camp, Abuja",
    lga: "Bwari",
    state: "FCT",
    ownership: "Private",
    bedCapacity: 80,
    operatingHours: "24/7",
    services: ["Robotic Surgery", "Fertility", "Cardiology", "General Surgery"],
    website: "https://nisa.com.ng",
    latitude: 9.0820,
    longitude: 7.4028,
  },
  {
    name: "Kelina Hospital Abuja",
    address: "Gwarimpa Estate, Abuja",
    lga: "Bwari",
    state: "FCT",
    ownership: "Private",
    bedCapacity: 50,
    operatingHours: "24/7",
    services: ["Laser Surgery", "Urology", "Endoscopy"],
    website: "https://kelinahospital.com",
    latitude: 9.1066,
    longitude: 7.3981,
  },
  {
    name: "Nizamiye Hospital",
    address: "Plot 186 Umaru Musa Yar'Adua Express Way, Life Camp, Abuja",
    lga: "Bwari",
    state: "FCT",
    ownership: "Private",
    bedCapacity: 60,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Obstetrics"],
    website: "https://nizamiye.ng",
    phone: "+234 805 633 9444",
    latitude: 9.0795,
    longitude: 7.4017,
  },
  {
    name: "Primus International Super Speciality Hospital",
    address: "Karu, Abuja",
    lga: "Karu",
    state: "FCT",
    ownership: "Private",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Orthopedics", "Cardiology", "Neurology"],
    latitude: 9.0239,
    longitude: 7.5766,
  },
  {
    name: "Garki Hospital",
    address: "Area 3, Garki, Abuja",
    lga: "Municipal Area Council",
    state: "FCT",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 9.0321,
    longitude: 7.4857,
  },
  {
    name: "Maitama District Hospital",
    address: "Aguiyi Ironsi Way, Maitama, Abuja",
    lga: "Municipal Area Council",
    state: "FCT",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Emergency", "Maternity"],
    latitude: 9.0879,
    longitude: 7.5007,
  },
  {
    name: "Wuse General Hospital",
    address: "Wuse Zone 4, Abuja",
    lga: "Municipal Area Council",
    state: "FCT",
    ownership: "Government",
    bedCapacity: 120,
    operatingHours: "24/7",
    services: ["General Medicine", "Pediatrics", "Obstetrics"],
    latitude: 9.0765,
    longitude: 7.4654,
  },

  // ============================================
  // NORTH CENTRAL STATES
  // ============================================

  // BENUE STATE
  {
    name: "Federal Medical Centre Makurdi",
    address: "Makurdi, Benue State",
    lga: "Makurdi",
    state: "Benue",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    website: "https://fmcmakurdi.org.ng",
    latitude: 7.7199,
    longitude: 8.5362,
  },
  {
    name: "Benue State University Teaching Hospital",
    address: "Makurdi, Benue State",
    lga: "Makurdi",
    state: "Benue",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 7.7321,
    longitude: 8.5189,
  },
  {
    name: "General Hospital Vandeikya",
    address: "Vandeikya, Benue State",
    lga: "Vandeikya",
    state: "Benue",
    ownership: "Government",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 7.0906,
    longitude: 9.0681,
  },
  {
    name: "General Hospital Katsina-Ala",
    address: "Katsina-Ala, Benue State",
    lga: "Katsina-Ala",
    state: "Benue",
    ownership: "Government",
    bedCapacity: 80,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity"],
    latitude: 7.1689,
    longitude: 9.2856,
  },

  // KOGI STATE
  {
    name: "Federal Medical Centre Lokoja",
    address: "Lokoja, Kogi State",
    lga: "Lokoja",
    state: "Kogi",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    website: "https://fmclokoja.gov.ng",
    latitude: 7.8023,
    longitude: 6.7333,
  },
  {
    name: "Kogi State Specialist Hospital",
    address: "Lokoja, Kogi State",
    lga: "Lokoja",
    state: "Kogi",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Obstetrics"],
    latitude: 7.7989,
    longitude: 6.7401,
  },
  {
    name: "General Hospital Okene",
    address: "Okene, Kogi State",
    lga: "Okene",
    state: "Kogi",
    ownership: "Government",
    bedCapacity: 120,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Pediatrics"],
    latitude: 7.5511,
    longitude: 6.2356,
  },

  // KWARA STATE
  {
    name: "University of Ilorin Teaching Hospital (UITH)",
    address: "Ilorin, Kwara State",
    lga: "Ilorin West",
    state: "Kwara",
    ownership: "Government",
    bedCapacity: 600,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Pediatrics"],
    website: "https://uith.org.ng",
    latitude: 8.4799,
    longitude: 4.5418,
  },
  {
    name: "Kwara State General Hospital",
    address: "Ilorin, Kwara State",
    lga: "Ilorin South",
    state: "Kwara",
    ownership: "Government",
    bedCapacity: 250,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 8.4966,
    longitude: 4.5426,
  },
  {
    name: "Civil Service Hospital Ilorin",
    address: "Ilorin, Kwara State",
    lga: "Ilorin West",
    state: "Kwara",
    ownership: "Government",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Pediatrics"],
    latitude: 8.4799,
    longitude: 4.5518,
  },

  // NASARAWA STATE
  {
    name: "Federal Medical Centre Keffi",
    address: "Keffi, Nasarawa State",
    lga: "Keffi",
    state: "Nasarawa",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics"],
    latitude: 8.8492,
    longitude: 7.8736,
  },
  {
    name: "Dalhatu Araf Specialist Hospital",
    address: "Lafia, Nasarawa State",
    lga: "Lafia",
    state: "Nasarawa",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine", "Cardiology"],
    latitude: 8.4966,
    longitude: 8.5156,
  },
  {
    name: "General Hospital Lafia",
    address: "Lafia, Nasarawa State",
    lga: "Lafia",
    state: "Nasarawa",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 8.4878,
    longitude: 8.5089,
  },

  // NIGER STATE
  {
    name: "Federal Medical Centre Bida",
    address: "Bida, Niger State",
    lga: "Bida",
    state: "Niger",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 9.0801,
    longitude: 6.0176,
  },
  {
    name: "General Hospital Minna",
    address: "Minna, Niger State",
    lga: "Chanchaga",
    state: "Niger",
    ownership: "Government",
    bedCapacity: 250,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 9.6139,
    longitude: 6.5568,
  },
  {
    name: "IBB Specialist Hospital Minna",
    address: "Minna, Niger State",
    lga: "Chanchaga",
    state: "Niger",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Cardiology", "Oncology"],
    latitude: 9.6219,
    longitude: 6.5489,
  },

  // PLATEAU STATE
  {
    name: "Jos University Teaching Hospital (JUTH)",
    address: "PMB 2076, Jos, Plateau State",
    lga: "Jos North",
    state: "Plateau",
    ownership: "Government",
    bedCapacity: 700,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Neurology", "Oncology", "Surgery"],
    website: "https://juth.org.ng",
    latitude: 9.9096,
    longitude: 8.8921,
  },
  {
    name: "Plateau Specialist Hospital Jos",
    address: "Jos, Plateau State",
    lga: "Jos South",
    state: "Plateau",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine"],
    latitude: 9.8965,
    longitude: 8.8583,
  },
  {
    name: "Bingham University Teaching Hospital",
    address: "Jos, Plateau State",
    lga: "Jos North",
    state: "Plateau",
    ownership: "Private",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Pediatrics"],
    latitude: 9.9187,
    longitude: 8.8856,
  },
  {
    name: "Our Lady of Apostles Hospital",
    address: "Jos, Plateau State",
    lga: "Jos North",
    state: "Plateau",
    ownership: "Private",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Surgery"],
    latitude: 9.9156,
    longitude: 8.8923,
  },

  // ============================================
  // NORTH EAST STATES
  // ============================================

  // ADAMAWA STATE
  {
    name: "Federal Medical Centre Yola",
    address: "Yola, Adamawa State",
    lga: "Yola South",
    state: "Adamawa",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 9.2035,
    longitude: 12.4954,
  },
  {
    name: "Modibbo Adama University Teaching Hospital",
    address: "Yola, Adamawa State",
    lga: "Yola North",
    state: "Adamawa",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    website: "https://mautech.edu.ng/teaching-hospital",
    latitude: 9.2189,
    longitude: 12.4821,
  },
  {
    name: "State Specialist Hospital Yola",
    address: "Yola, Adamawa State",
    lga: "Yola South",
    state: "Adamawa",
    ownership: "Government",
    bedCapacity: 250,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Obstetrics"],
    latitude: 9.2099,
    longitude: 12.4889,
  },

  // BAUCHI STATE
  {
    name: "Federal Medical Centre Azare",
    address: "Azare, Bauchi State",
    lga: "Katagum",
    state: "Bauchi",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics"],
    latitude: 11.6806,
    longitude: 10.1914,
  },
  {
    name: "Abubakar Tafawa Balewa University Teaching Hospital",
    address: "Bauchi, Bauchi State",
    lga: "Bauchi",
    state: "Bauchi",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 10.3105,
    longitude: 9.8461,
  },
  {
    name: "General Hospital Bauchi",
    address: "Bauchi, Bauchi State",
    lga: "Bauchi",
    state: "Bauchi",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 10.3156,
    longitude: 9.8401,
  },

  // BORNO STATE
  {
    name: "University of Maiduguri Teaching Hospital",
    address: "Bama Road, Maiduguri, Borno State",
    lga: "Maiduguri",
    state: "Borno",
    ownership: "Government",
    bedCapacity: 750,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Neurology"],
    website: "https://umth.edu.ng",
    latitude: 11.8333,
    longitude: 13.1500,
  },
  {
    name: "State Specialist Hospital Maiduguri",
    address: "Maiduguri, Borno State",
    lga: "Maiduguri",
    state: "Borno",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine"],
    latitude: 11.8456,
    longitude: 13.1589,
  },
  {
    name: "Umaru Shehu Ultra-Modern Hospital",
    address: "Maiduguri, Borno State",
    lga: "Maiduguri",
    state: "Borno",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Emergency"],
    latitude: 11.8521,
    longitude: 13.1423,
  },

  // GOMBE STATE
  {
    name: "Federal Teaching Hospital Gombe",
    address: "Gombe, Gombe State",
    lga: "Gombe",
    state: "Gombe",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 10.2897,
    longitude: 11.1673,
  },
  {
    name: "State Specialist Hospital Gombe",
    address: "Gombe, Gombe State",
    lga: "Gombe",
    state: "Gombe",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Obstetrics"],
    latitude: 10.2856,
    longitude: 11.1701,
  },

  // TARABA STATE
  {
    name: "Federal Medical Centre Jalingo",
    address: "Jalingo, Taraba State",
    lga: "Jalingo",
    state: "Taraba",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 8.8906,
    longitude: 11.3597,
  },
  {
    name: "State Specialist Hospital Jalingo",
    address: "Jalingo, Taraba State",
    lga: "Jalingo",
    state: "Taraba",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Maternity"],
    latitude: 8.8856,
    longitude: 11.3656,
  },

  // YOBE STATE
  {
    name: "Federal Medical Centre Nguru",
    address: "Nguru, Yobe State",
    lga: "Nguru",
    state: "Yobe",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics"],
    latitude: 12.8794,
    longitude: 10.4531,
  },
  {
    name: "State Specialist Hospital Damaturu",
    address: "Damaturu, Yobe State",
    lga: "Damaturu",
    state: "Yobe",
    ownership: "Government",
    bedCapacity: 250,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine"],
    latitude: 11.7500,
    longitude: 11.9667,
  },
  {
    name: "General Hospital Geidam",
    address: "Geidam, Yobe State",
    lga: "Geidam",
    state: "Yobe",
    ownership: "Government",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity"],
    latitude: 12.8989,
    longitude: 11.9278,
  },

  // ============================================
  // NORTH WEST STATES
  // ============================================

  // JIGAWA STATE
  {
    name: "Federal Medical Centre Birnin Kudu",
    address: "Birnin Kudu, Jigawa State",
    lga: "Birnin Kudu",
    state: "Jigawa",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics"],
    latitude: 11.4533,
    longitude: 9.4917,
  },
  {
    name: "Rasheed Shekoni Teaching Hospital Dutse",
    address: "Dutse, Jigawa State",
    lga: "Dutse",
    state: "Jigawa",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 11.7561,
    longitude: 9.3383,
  },
  {
    name: "General Hospital Hadejia",
    address: "Hadejia, Jigawa State",
    lga: "Hadejia",
    state: "Jigawa",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 12.4500,
    longitude: 10.0444,
  },

  // KADUNA STATE
  {
    name: "Ahmadu Bello University Teaching Hospital Zaria",
    address: "Shika, Zaria, Kaduna State",
    lga: "Zaria",
    state: "Kaduna",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Neurology", "Oncology", "Surgery"],
    website: "https://abuth.gov.ng",
    latitude: 11.1278,
    longitude: 7.6839,
  },
  {
    name: "Barau Dikko Teaching Hospital Kaduna",
    address: "Kaduna, Kaduna State",
    lga: "Kaduna North",
    state: "Kaduna",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 10.5222,
    longitude: 7.4403,
  },
  {
    name: "44 Nigerian Army Reference Hospital Kaduna",
    address: "Kaduna, Kaduna State",
    lga: "Kaduna South",
    state: "Kaduna",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine", "Orthopedics"],
    latitude: 10.5156,
    longitude: 7.4389,
  },
  {
    name: "St. Gerard's Catholic Hospital",
    address: "Kaduna, Kaduna State",
    lga: "Kaduna North",
    state: "Kaduna",
    ownership: "Private",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 10.5289,
    longitude: 7.4456,
  },

  // KANO STATE
  {
    name: "Aminu Kano Teaching Hospital",
    address: "Zaria Road, Kano",
    lga: "Tarauni",
    state: "Kano",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Neurology", "Surgery"],
    website: "https://akth.org.ng",
    latitude: 11.9646,
    longitude: 8.4989,
  },
  {
    name: "Murtala Muhammad Specialist Hospital",
    address: "Kano City, Kano",
    lga: "Kano Municipal",
    state: "Kano",
    ownership: "Government",
    bedCapacity: 600,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine", "Trauma"],
    latitude: 11.9969,
    longitude: 8.5167,
  },
  {
    name: "Muhammad Abdullahi Wase Teaching Hospital",
    address: "Hospital Road, Kano",
    lga: "Nassarawa",
    state: "Kano",
    ownership: "Government",
    bedCapacity: 450,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Obstetrics"],
    latitude: 11.9856,
    longitude: 8.5089,
  },
  {
    name: "Hasiya Bayero Pediatric Hospital",
    address: "Kano, Kano State",
    lga: "Kano Municipal",
    state: "Kano",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["Pediatrics", "Neonatal Care", "Child Surgery"],
    latitude: 11.9967,
    longitude: 8.5234,
  },

  // KATSINA STATE
  {
    name: "Federal Medical Centre Katsina",
    address: "Katsina, Katsina State",
    lga: "Katsina",
    state: "Katsina",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 13.0059,
    longitude: 7.5984,
  },
  {
    name: "General Hospital Katsina",
    address: "Katsina, Katsina State",
    lga: "Katsina",
    state: "Katsina",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 13.0089,
    longitude: 7.6012,
  },
  {
    name: "General Hospital Daura",
    address: "Daura, Katsina State",
    lga: "Daura",
    state: "Katsina",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Pediatrics"],
    latitude: 13.0333,
    longitude: 8.3167,
  },

  // KEBBI STATE
  {
    name: "Federal Medical Centre Birnin Kebbi",
    address: "Birnin Kebbi, Kebbi State",
    lga: "Birnin Kebbi",
    state: "Kebbi",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics"],
    latitude: 12.4539,
    longitude: 4.1975,
  },
  {
    name: "Sir Yahaya Memorial Hospital",
    address: "Birnin Kebbi, Kebbi State",
    lga: "Birnin Kebbi",
    state: "Kebbi",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine"],
    latitude: 12.4589,
    longitude: 4.2012,
  },

  // SOKOTO STATE
  {
    name: "Usmanu Danfodiyo University Teaching Hospital",
    address: "Sokoto, Sokoto State",
    lga: "Sokoto South",
    state: "Sokoto",
    ownership: "Government",
    bedCapacity: 700,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Neurology"],
    website: "https://uduth.org.ng",
    latitude: 13.0628,
    longitude: 5.2339,
  },
  {
    name: "Specialist Hospital Sokoto",
    address: "Sokoto, Sokoto State",
    lga: "Sokoto North",
    state: "Sokoto",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine"],
    latitude: 13.0589,
    longitude: 5.2389,
  },
  {
    name: "Women and Children Hospital Sokoto",
    address: "Sokoto, Sokoto State",
    lga: "Sokoto South",
    state: "Sokoto",
    ownership: "Government",
    bedCapacity: 250,
    operatingHours: "24/7",
    services: ["Obstetrics", "Gynecology", "Pediatrics"],
    latitude: 13.0656,
    longitude: 5.2267,
  },

  // ZAMFARA STATE
  {
    name: "Federal Medical Centre Gusau",
    address: "Gusau, Zamfara State",
    lga: "Gusau",
    state: "Zamfara",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 12.1704,
    longitude: 6.6631,
  },
  {
    name: "Ahmad Sani Yariman Bakura Specialist Hospital",
    address: "Gusau, Zamfara State",
    lga: "Gusau",
    state: "Zamfara",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Cardiology", "Surgery", "Internal Medicine"],
    latitude: 12.1656,
    longitude: 6.6589,
  },

  // ============================================
  // SOUTH EAST STATES
  // ============================================

  // ABIA STATE
  {
    name: "Federal Medical Centre Umuahia",
    address: "Umuahia, Abia State",
    lga: "Umuahia North",
    state: "Abia",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 5.5319,
    longitude: 7.4866,
  },
  {
    name: "Abia State University Teaching Hospital",
    address: "Aba, Abia State",
    lga: "Aba North",
    state: "Abia",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 5.1067,
    longitude: 7.3667,
  },
  {
    name: "General Hospital Aba",
    address: "Aba, Abia State",
    lga: "Aba South",
    state: "Abia",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 5.1167,
    longitude: 7.3500,
  },

  // ANAMBRA STATE
  {
    name: "Nnamdi Azikiwe University Teaching Hospital Nnewi",
    address: "Nnewi, Anambra State",
    lga: "Nnewi North",
    state: "Anambra",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Neurology"],
    website: "https://nauth.org.ng",
    latitude: 6.0197,
    longitude: 6.9194,
  },
  {
    name: "Chukwuemeka Odumegwu Ojukwu University Teaching Hospital",
    address: "Awka, Anambra State",
    lga: "Awka South",
    state: "Anambra",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 6.2088,
    longitude: 7.0742,
  },
  {
    name: "St. Charles Borromeo Hospital",
    address: "Onitsha, Anambra State",
    lga: "Onitsha North",
    state: "Anambra",
    ownership: "Private",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity", "Pediatrics"],
    latitude: 6.1500,
    longitude: 6.7833,
  },

  // EBONYI STATE
  {
    name: "Alex Ekwueme Federal University Teaching Hospital Abakaliki",
    address: "Abakaliki, Ebonyi State",
    lga: "Abakaliki",
    state: "Ebonyi",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Oncology"],
    website: "https://aefutha.edu.ng",
    latitude: 6.3249,
    longitude: 8.1137,
  },
  {
    name: "Mile Four Hospital Abakaliki",
    address: "Abakaliki, Ebonyi State",
    lga: "Abakaliki",
    state: "Ebonyi",
    ownership: "Private",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 6.3189,
    longitude: 8.1089,
  },

  // ENUGU STATE
  {
    name: "University of Nigeria Teaching Hospital Enugu",
    address: "Ituku-Ozalla, Enugu",
    lga: "Enugu South",
    state: "Enugu",
    ownership: "Government",
    bedCapacity: 700,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Neurology", "Oncology", "Surgery"],
    website: "https://unth.org.ng",
    latitude: 6.4167,
    longitude: 7.5000,
  },
  {
    name: "Enugu State University Teaching Hospital Parklane",
    address: "Parklane, Enugu",
    lga: "Enugu North",
    state: "Enugu",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 6.4489,
    longitude: 7.5067,
  },
  {
    name: "National Orthopaedic Hospital Enugu",
    address: "Enugu, Enugu State",
    lga: "Enugu North",
    state: "Enugu",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["Orthopedics", "Trauma Surgery", "Physiotherapy"],
    latitude: 6.4556,
    longitude: 7.5089,
  },
  {
    name: "Niger Foundation Hospital",
    address: "Enugu, Enugu State",
    lga: "Enugu South",
    state: "Enugu",
    ownership: "Private",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 6.4234,
    longitude: 7.4989,
  },

  // IMO STATE
  {
    name: "Federal Medical Centre Owerri",
    address: "Owerri, Imo State",
    lga: "Owerri Municipal",
    state: "Imo",
    ownership: "Government",
    bedCapacity: 450,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    website: "https://fmcowerri.org.ng",
    latitude: 5.4836,
    longitude: 7.0333,
  },
  {
    name: "Imo State Specialist Hospital",
    address: "Owerri, Imo State",
    lga: "Owerri Municipal",
    state: "Imo",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine"],
    latitude: 5.4889,
    longitude: 7.0267,
  },
  {
    name: "General Hospital Orlu",
    address: "Orlu, Imo State",
    lga: "Orlu",
    state: "Imo",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 5.7961,
    longitude: 7.0342,
  },

  // ============================================
  // SOUTH SOUTH STATES
  // ============================================

  // AKWA IBOM STATE
  {
    name: "University of Uyo Teaching Hospital",
    address: "Uyo, Akwa Ibom State",
    lga: "Uyo",
    state: "Akwa Ibom",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Oncology"],
    website: "https://uuth.org.ng",
    latitude: 5.0377,
    longitude: 7.9128,
  },
  {
    name: "Ibom Specialist Hospital",
    address: "Uyo, Akwa Ibom State",
    lga: "Uyo",
    state: "Akwa Ibom",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Cardiology", "Surgery", "Internal Medicine"],
    latitude: 5.0412,
    longitude: 7.9089,
  },
  {
    name: "General Hospital Ikot Ekpene",
    address: "Ikot Ekpene, Akwa Ibom State",
    lga: "Ikot Ekpene",
    state: "Akwa Ibom",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 5.1833,
    longitude: 7.7167,
  },
  {
    name: "Immanuel General Hospital Eket",
    address: "Eket, Akwa Ibom State",
    lga: "Eket",
    state: "Akwa Ibom",
    ownership: "Private",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Pediatrics"],
    latitude: 4.6500,
    longitude: 7.9333,
  },

  // BAYELSA STATE
  {
    name: "Federal Medical Centre Yenagoa",
    address: "Yenagoa, Bayelsa State",
    lga: "Yenagoa",
    state: "Bayelsa",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 4.9267,
    longitude: 6.2676,
  },
  {
    name: "Niger Delta University Teaching Hospital",
    address: "Okolobiri, Bayelsa State",
    lga: "Yenagoa",
    state: "Bayelsa",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 4.9456,
    longitude: 6.2789,
  },
  {
    name: "Bayelsa Specialist Hospital",
    address: "Yenagoa, Bayelsa State",
    lga: "Yenagoa",
    state: "Bayelsa",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Maternity"],
    latitude: 4.9189,
    longitude: 6.2612,
  },

  // CROSS RIVER STATE
  {
    name: "University of Calabar Teaching Hospital",
    address: "Calabar, Cross River State",
    lga: "Calabar Municipality",
    state: "Cross River",
    ownership: "Government",
    bedCapacity: 600,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Neurology"],
    website: "https://ucth.gov.ng",
    latitude: 4.9589,
    longitude: 8.3367,
  },
  {
    name: "General Hospital Calabar",
    address: "Calabar, Cross River State",
    lga: "Calabar South",
    state: "Cross River",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 4.9512,
    longitude: 8.3289,
  },
  {
    name: "General Hospital Ogoja",
    address: "Ogoja, Cross River State",
    lga: "Ogoja",
    state: "Cross River",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Pediatrics"],
    latitude: 6.6558,
    longitude: 8.7992,
  },

  // DELTA STATE
  {
    name: "Federal Medical Centre Asaba",
    address: "Asaba, Delta State",
    lga: "Oshimili South",
    state: "Delta",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 6.1956,
    longitude: 6.7344,
  },
  {
    name: "Delta State University Teaching Hospital Oghara",
    address: "Oghara, Delta State",
    lga: "Ethiope West",
    state: "Delta",
    ownership: "Government",
    bedCapacity: 450,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Oncology"],
    latitude: 5.9000,
    longitude: 5.9000,
  },
  {
    name: "Central Hospital Warri",
    address: "Warri, Delta State",
    lga: "Warri South",
    state: "Delta",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity", "Emergency"],
    latitude: 5.5167,
    longitude: 5.7500,
  },
  {
    name: "Central Hospital Agbor",
    address: "Agbor, Delta State",
    lga: "Ika South",
    state: "Delta",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 6.2500,
    longitude: 6.1833,
  },

  // EDO STATE
  {
    name: "University of Benin Teaching Hospital",
    address: "Benin City, Edo State",
    lga: "Egor",
    state: "Edo",
    ownership: "Government",
    bedCapacity: 900,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Neurology", "Surgery"],
    website: "https://ubth.org",
    latitude: 6.3414,
    longitude: 5.6198,
  },
  {
    name: "Irrua Specialist Teaching Hospital",
    address: "Irrua, Edo State",
    lga: "Esan Central",
    state: "Edo",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Lassa Fever Treatment", "Surgery", "Internal Medicine"],
    latitude: 6.7500,
    longitude: 6.2333,
  },
  {
    name: "Central Hospital Benin City",
    address: "Benin City, Edo State",
    lga: "Oredo",
    state: "Edo",
    ownership: "Government",
    bedCapacity: 450,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity", "Pediatrics"],
    latitude: 6.3350,
    longitude: 5.6037,
  },
  {
    name: "Stella Obasanjo Hospital",
    address: "Benin City, Edo State",
    lga: "Oredo",
    state: "Edo",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["Obstetrics", "Gynecology", "Pediatrics"],
    latitude: 6.3389,
    longitude: 5.6089,
  },

  // RIVERS STATE
  {
    name: "University of Port Harcourt Teaching Hospital",
    address: "Alakahia, Port Harcourt, Rivers State",
    lga: "Obio-Akpor",
    state: "Rivers",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Neurology", "Surgery"],
    website: "https://upth.gov.ng",
    latitude: 4.8769,
    longitude: 6.9219,
  },
  {
    name: "Rivers State University Teaching Hospital",
    address: "Port Harcourt, Rivers State",
    lga: "Port Harcourt",
    state: "Rivers",
    ownership: "Government",
    bedCapacity: 450,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 4.8156,
    longitude: 7.0089,
  },
  {
    name: "Braithwaite Memorial Specialist Hospital",
    address: "Port Harcourt, Rivers State",
    lga: "Port Harcourt",
    state: "Rivers",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 4.7689,
    longitude: 7.0123,
  },
  {
    name: "Lily Hospitals Port Harcourt",
    address: "Port Harcourt, Rivers State",
    lga: "Obio-Akpor",
    state: "Rivers",
    ownership: "Private",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Orthopedics", "Fertility"],
    latitude: 4.8512,
    longitude: 6.9856,
  },
  {
    name: "First Rivers Hospital",
    address: "250 PH/Aba Expressway, Rumuomasi, Port Harcourt",
    lga: "Obio-Akpor",
    state: "Rivers",
    ownership: "Private",
    bedCapacity: 60,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 4.8356,
    longitude: 7.0012,
  },

  // ============================================
  // SOUTH WEST STATES (excluding Lagos - already done)
  // ============================================

  // EKITI STATE
  {
    name: "Federal Teaching Hospital Ido-Ekiti",
    address: "Ido-Ekiti, Ekiti State",
    lga: "Ido-Osi",
    state: "Ekiti",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    website: "https://fthidoekiti.org.ng",
    latitude: 7.8000,
    longitude: 5.2000,
  },
  {
    name: "Ekiti State University Teaching Hospital",
    address: "Ado-Ekiti, Ekiti State",
    lga: "Ado-Ekiti",
    state: "Ekiti",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 7.6211,
    longitude: 5.2214,
  },
  {
    name: "State Specialist Hospital Ikere-Ekiti",
    address: "Ikere-Ekiti, Ekiti State",
    lga: "Ikere",
    state: "Ekiti",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Maternity"],
    latitude: 7.4975,
    longitude: 5.2256,
  },

  // OGUN STATE
  {
    name: "Federal Medical Centre Abeokuta",
    address: "Abeokuta, Ogun State",
    lga: "Abeokuta South",
    state: "Ogun",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    website: "https://fmcabeokuta.net",
    latitude: 7.1575,
    longitude: 3.3514,
  },
  {
    name: "Olabisi Onabanjo University Teaching Hospital",
    address: "Sagamu, Ogun State",
    lga: "Sagamu",
    state: "Ogun",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Oncology"],
    latitude: 6.8500,
    longitude: 3.6500,
  },
  {
    name: "State Hospital Ijaiye Abeokuta",
    address: "Abeokuta, Ogun State",
    lga: "Abeokuta North",
    state: "Ogun",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 7.1689,
    longitude: 3.3456,
  },
  {
    name: "Babcock University Teaching Hospital",
    address: "Ilishan-Remo, Ogun State",
    lga: "Ikenne",
    state: "Ogun",
    ownership: "Private",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 6.9000,
    longitude: 3.7167,
  },

  // ONDO STATE
  {
    name: "Federal Medical Centre Owo",
    address: "Owo, Ondo State",
    lga: "Owo",
    state: "Ondo",
    ownership: "Government",
    bedCapacity: 450,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics", "Internal Medicine"],
    latitude: 7.1961,
    longitude: 5.5878,
  },
  {
    name: "University of Medical Sciences Teaching Hospital Akure",
    address: "Akure, Ondo State",
    lga: "Akure South",
    state: "Ondo",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 7.2500,
    longitude: 5.1950,
  },
  {
    name: "State Specialist Hospital Akure",
    address: "Akure, Ondo State",
    lga: "Akure South",
    state: "Ondo",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Surgery", "Maternity"],
    latitude: 7.2556,
    longitude: 5.2012,
  },
  {
    name: "Mother and Child Hospital Akure",
    address: "Akure, Ondo State",
    lga: "Akure South",
    state: "Ondo",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["Obstetrics", "Gynecology", "Pediatrics", "Neonatal Care"],
    latitude: 7.2467,
    longitude: 5.1889,
  },

  // OSUN STATE
  {
    name: "Obafemi Awolowo University Teaching Hospital Ile-Ife",
    address: "Ile-Ife, Osun State",
    lga: "Ife Central",
    state: "Osun",
    ownership: "Government",
    bedCapacity: 600,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Surgery", "Neurology"],
    website: "https://oauthc.org.ng",
    latitude: 7.4667,
    longitude: 4.5667,
  },
  {
    name: "State Hospital Asubiaro Osogbo",
    address: "Osogbo, Osun State",
    lga: "Osogbo",
    state: "Osun",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 7.7833,
    longitude: 4.5833,
  },
  {
    name: "Ladoke Akintola University Teaching Hospital Osogbo",
    address: "Osogbo, Osun State",
    lga: "Osogbo",
    state: "Osun",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine"],
    latitude: 7.7767,
    longitude: 4.5756,
  },
  {
    name: "General Hospital Ilesa",
    address: "Ilesa, Osun State",
    lga: "Ilesa East",
    state: "Osun",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Pediatrics"],
    latitude: 7.6167,
    longitude: 4.7333,
  },

  // OYO STATE
  {
    name: "University College Hospital Ibadan",
    address: "Queen Elizabeth Road, Ibadan",
    lga: "Ibadan North",
    state: "Oyo",
    ownership: "Government",
    bedCapacity: 850,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Cardiology", "Oncology", "Neurology", "Surgery", "Transplant"],
    website: "https://uch-ibadan.org.ng",
    latitude: 7.4000,
    longitude: 3.9000,
  },
  {
    name: "Ladoke Akintola University Teaching Hospital Ogbomoso",
    address: "Ogbomoso, Oyo State",
    lga: "Ogbomoso North",
    state: "Oyo",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Teaching Hospital", "Surgery", "Internal Medicine", "Pediatrics"],
    latitude: 8.1333,
    longitude: 4.2500,
  },
  {
    name: "Ring Road State Hospital Ibadan",
    address: "Ring Road, Ibadan",
    lga: "Ibadan South West",
    state: "Oyo",
    ownership: "Government",
    bedCapacity: 350,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 7.3856,
    longitude: 3.8767,
  },
  {
    name: "Adeoyo Maternity Teaching Hospital",
    address: "Yemetu, Ibadan",
    lga: "Ibadan North",
    state: "Oyo",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["Obstetrics", "Gynecology", "Neonatal Care"],
    latitude: 7.4089,
    longitude: 3.8923,
  },
  {
    name: "Jericho Nursing Home Ibadan",
    address: "Jericho, Ibadan",
    lga: "Ibadan North West",
    state: "Oyo",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Pediatrics"],
    latitude: 7.3967,
    longitude: 3.8656,
  },
  {
    name: "Vine Branch Hospital Ibadan",
    address: "Ibadan, Oyo State",
    lga: "Ibadan South East",
    state: "Oyo",
    ownership: "Private",
    bedCapacity: 80,
    operatingHours: "24/7",
    services: ["Multi-Specialty", "Fertility", "Surgery"],
    latitude: 7.3789,
    longitude: 3.9012,
  },
];

async function seedNigeria() {
  console.log("Seeding database with Nigerian hospitals from all 36 states + FCT...");
  
  try {
    await db.insert(hospitals).values(nigeriaHospitals);
    console.log(`Successfully seeded ${nigeriaHospitals.length} hospitals across Nigeria`);
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
  
  process.exit(0);
}

seedNigeria();
