import { db } from "./db";
import { hospitals } from "@shared/schema";

const moreHospitals = [
  {
    name: "Grandville Medical and Laser",
    address: "3 Coker Road, Ilupeju, Lagos",
    lga: "Mushin",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 25,
    operatingHours: "24/7",
    services: ["Laser Surgery", "Dermatology", "General Medicine"],
    latitude: 6.5519,
    longitude: 3.3584,
  },
  {
    name: "Rainbow Specialist Medical Centre",
    address: "29 Association Avenue, Ilupeju, Lagos",
    lga: "Mushin",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 40,
    operatingHours: "24/7",
    services: ["Pediatrics", "Gynecology", "Internal Medicine"],
    latitude: 6.5542,
    longitude: 3.3511,
  },
  {
    name: "Diamond Hospital",
    address: "8 Off Awolowo Road, Ikoyi, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 30,
    operatingHours: "24/7",
    services: ["General Surgery", "Orthopedics", "Emergency"],
    latitude: 6.4512,
    longitude: 3.4301,
  },
  {
    name: "Optimal Cancer Care Foundation",
    address: "40 Montgomery Road, Yaba, Lagos",
    lga: "Yaba",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 20,
    operatingHours: "8am - 6pm",
    services: ["Oncology", "Chemotherapy", "Radiotherapy"],
    latitude: 6.5089,
    longitude: 3.3721,
  },
  {
    name: "Lagos Executive Cardiovascular Centre",
    address: "Victoria Garden City, Lekki, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 45,
    operatingHours: "24/7",
    services: ["Cardiology", "Cardiac Surgery", "Rehabilitation"],
    latitude: 6.4401,
    longitude: 3.5422,
  },
  {
    name: "Isolo General Hospital",
    address: "Isolo Road, Isolo, Lagos",
    lga: "Oshodi-Isolo",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 6.5317,
    longitude: 3.3231,
  },
  {
    name: "Agege General Hospital",
    address: "Agege Motor Road, Agege, Lagos",
    lga: "Agege",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 120,
    operatingHours: "24/7",
    services: ["General Medicine", "Pediatrics", "Emergency"],
    latitude: 6.6164,
    longitude: 3.3233,
  },
  {
    name: "Orile-Agege General Hospital",
    address: "Orile-Agege, Lagos",
    lga: "Ifako-Ijaiye",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity"],
    latitude: 6.6399,
    longitude: 3.3138,
  },
  {
    name: "Harvey Road General Hospital",
    address: "Harvey Road, Yaba, Lagos",
    lga: "Yaba",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 80,
    operatingHours: "24/7",
    services: ["General Medicine", "Pediatrics"],
    latitude: 6.5151,
    longitude: 3.3745,
  },
  {
    name: "Apapa General Hospital",
    address: "Apapa, Lagos",
    lga: "Apapa",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity"],
    latitude: 6.4488,
    longitude: 3.3644,
  },
  {
    name: "Surulere General Hospital",
    address: "Ojuelegba Road, Surulere, Lagos",
    lga: "Surulere",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 120,
    operatingHours: "24/7",
    services: ["General Medicine", "Emergency", "Pediatrics"],
    latitude: 6.5001,
    longitude: 3.3544,
  },
  {
    name: "Ojo General Hospital",
    address: "Alaba, Ojo, Lagos",
    lga: "Ojo",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 90,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity"],
    latitude: 6.4567,
    longitude: 3.1912,
  },
  {
    name: "Ajeromi General Hospital",
    address: "Ajegunle, Lagos",
    lga: "Ajeromi-Ifelodun",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 80,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 6.4501,
    longitude: 3.3311,
  },
  {
    name: "Massey Street Children Hospital",
    address: "Massey Street, Lagos Island",
    lga: "Lagos Island",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 60,
    operatingHours: "24/7",
    services: ["Pediatrics", "Neonatal Care", "Immunization"],
    latitude: 6.4522,
    longitude: 3.3921,
  },
  {
    name: "Amuwo-Odofin General Hospital",
    address: "Festac Town, Lagos",
    lga: "Amuwo-Odofin",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Surgery"],
    latitude: 6.4671,
    longitude: 3.2912,
  },
  {
    name: "Iwaya Health Centre",
    address: "Iwaya, Yaba, Lagos",
    lga: "Yaba",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 30,
    operatingHours: "8am - 5pm",
    services: ["Primary Care", "Immunization", "Antenatal"],
    latitude: 6.5123,
    longitude: 3.3856,
  },
  {
    name: "Randle General Hospital",
    address: "Randle Avenue, Surulere, Lagos",
    lga: "Surulere",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 110,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Obstetrics"],
    latitude: 6.4912,
    longitude: 3.3512,
  },
  {
    name: "Lagos Island Maternity Hospital",
    address: "Campos Square, Lagos Island",
    lga: "Lagos Island",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["Obstetrics", "Gynecology", "Neonatal Care"],
    latitude: 6.4541,
    longitude: 3.3941,
  },
  {
    name: "Ifako-Ijaiye General Hospital",
    address: "College Road, Ifako-Ijaiye, Lagos",
    lga: "Ifako-Ijaiye",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 80,
    operatingHours: "24/7",
    services: ["General Medicine", "Pediatrics", "Maternity"],
    latitude: 6.6521,
    longitude: 3.3045,
  },
  {
    name: "Oriwu Model Health Centre",
    address: "Ikorodu, Lagos",
    lga: "Ikorodu",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 40,
    operatingHours: "8am - 6pm",
    services: ["Primary Care", "Maternal Health", "Child Health"],
    latitude: 6.6123,
    longitude: 3.5112,
  },
  {
    name: "Lancet Laboratories",
    address: "10B Idejo Street, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 10,
    operatingHours: "7am - 7pm",
    services: ["Laboratory", "Diagnostics", "Health Screening"],
    latitude: 6.4289,
    longitude: 3.4189,
  },
  {
    name: "Clina-Lancet Laboratories",
    address: "54 Isaac John Street, GRA Ikeja",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 5,
    operatingHours: "7am - 7pm",
    services: ["Laboratory", "Pathology", "DNA Testing"],
    latitude: 6.5812,
    longitude: 3.3512,
  },
  {
    name: "City Clinic",
    address: "6 Maitama Sule Street, Ikoyi, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 20,
    operatingHours: "24/7",
    services: ["General Practice", "Travel Medicine", "Vaccinations"],
    latitude: 6.4512,
    longitude: 3.4312,
  },
  {
    name: "Vedic Lifecare Hospital",
    address: "27 Babatunde Anjous Avenue, Lekki Phase 1",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 50,
    operatingHours: "24/7",
    services: ["Cardiology", "Neurology", "Pediatrics", "IVF"],
    latitude: 6.4398,
    longitude: 3.4612,
  },
  {
    name: "Medicaid Radio-Diagnostic Centre",
    address: "15 Oba Akinjobi Way, Ikeja GRA",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 15,
    operatingHours: "8am - 8pm",
    services: ["Radiology", "MRI", "CT Scan", "Ultrasound"],
    latitude: 6.5823,
    longitude: 3.3445,
  },
  {
    name: "Vision Healthcare Centre",
    address: "Plot 7 Block B, Acme Road, Ogba",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 30,
    operatingHours: "24/7",
    services: ["Ophthalmology", "Optometry", "Eye Surgery"],
    latitude: 6.6134,
    longitude: 3.3367,
  },
  {
    name: "Med-In Women and Children Hospital",
    address: "17 Ajiran Road, Agungi, Lekki",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 35,
    operatingHours: "24/7",
    services: ["Obstetrics", "Gynecology", "Pediatrics", "Fertility"],
    latitude: 6.4321,
    longitude: 3.5112,
  },
  {
    name: "Lily Hospitals",
    address: "6 Mafe Street, Off Baale Street, Ajah",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 40,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity", "Pediatrics"],
    latitude: 6.4689,
    longitude: 3.5756,
  },
  {
    name: "Gold Cross Hospital",
    address: "34 Adeniyi Jones Avenue, Ikeja",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 55,
    operatingHours: "24/7",
    services: ["General Surgery", "Orthopedics", "Internal Medicine"],
    latitude: 6.5956,
    longitude: 3.3567,
  },
  {
    name: "Ibeju Lekki General Hospital",
    address: "Ibeju Lekki, Lagos",
    lga: "Ibeju-Lekki",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 60,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 6.4589,
    longitude: 3.7512,
  },
  {
    name: "Tolu Medical Centre",
    address: "32 Adeyemo Alakija Street, Victoria Island",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 25,
    operatingHours: "24/7",
    services: ["General Practice", "Pharmacy", "Laboratory"],
    latitude: 6.4234,
    longitude: 3.4189,
  },
  {
    name: "Eti-Osa Primary Health Centre",
    address: "Ajah, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 20,
    operatingHours: "8am - 5pm",
    services: ["Primary Care", "Immunization", "Maternal Health"],
    latitude: 6.4612,
    longitude: 3.5634,
  },
  {
    name: "Beta Healthcare",
    address: "Plot 2, Block 5, Ogba Industrial Scheme",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 30,
    operatingHours: "24/7",
    services: ["General Medicine", "Diagnostics", "Minor Surgery"],
    latitude: 6.6212,
    longitude: 3.3312,
  },
  {
    name: "Crystal Specialist Hospital",
    address: "22 Arowojobe Street, Oshodi",
    lga: "Oshodi-Isolo",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 45,
    operatingHours: "24/7",
    services: ["Surgery", "Obstetrics", "Pediatrics", "Dental"],
    latitude: 6.5512,
    longitude: 3.3412,
  },
  {
    name: "Neuropsychiatric Hospital, Yaba",
    address: "Harvey Road, Yaba, Lagos",
    lga: "Yaba",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 500,
    operatingHours: "24/7",
    services: ["Psychiatry", "Mental Health", "Rehabilitation"],
    latitude: 6.5178,
    longitude: 3.3789,
  },
];

async function seedMore() {
  console.log("Adding more Lagos hospitals...");
  
  try {
    await db.insert(hospitals).values(moreHospitals);
    console.log(`Successfully added ${moreHospitals.length} more hospitals`);
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
  
  process.exit(0);
}

seedMore();
