import { db } from "./db";
import { hospitals } from "@shared/schema";

const lagosHospitals = [
  {
    name: "Lagos University Teaching Hospital (LUTH)",
    address: "Ishaga Rd, Idi-Araba, Lagos",
    lga: "Mushin",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 800,
    operatingHours: "24/7",
    services: ["Oncology", "Dentistry", "Pediatrics", "Surgery", "Emergency", "Radiology"],
    email: "info@luth.gov.ng",
    latitude: 6.5244,
    longitude: 3.3556,
  },
  {
    name: "Lagos State University Teaching Hospital (LASUTH)",
    address: "1-5 Oba Akinjobi Way, Ikeja, Lagos",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 400,
    operatingHours: "24/7",
    services: ["Critical Care", "Surgery", "Pediatrics", "Internal Medicine", "Trauma"],
    email: "enquiry@lasuth.org.ng",
    latitude: 6.5956,
    longitude: 3.3421,
  },
  {
    name: "Reddington Hospital",
    address: "12 Idowu Martins St, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 132,
    operatingHours: "24/7",
    services: ["Cardiology", "Gastroenterology", "Nephrology", "Surgery", "Maternity"],
    email: "info@reddingtonhospital.com",
    latitude: 6.4285,
    longitude: 3.4225,
  },
  {
    name: "Lagoon Hospitals (Victoria Island)",
    address: "17B Bishop Aboyade Cole St, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 50,
    operatingHours: "24/7",
    services: ["Orthopedics", "Trauma", "Surgery", "General Medicine"],
    latitude: 6.4281,
    longitude: 3.4219,
  },
  {
    name: "St. Nicholas Hospital",
    address: "57 Campbell St, Lagos Island, Lagos",
    lga: "Lagos Island",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 50,
    operatingHours: "24/7",
    services: ["Nephrology", "Kidney Transplant", "Oncology", "Dialysis"],
    latitude: 6.4531,
    longitude: 3.3958,
  },
  {
    name: "Gbagada General Hospital",
    address: "1 Hospital Rd, Araromi, Gbagada, Lagos",
    lga: "Kosofe",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Dialysis", "Cardiology", "Emergency"],
    latitude: 6.5569,
    longitude: 3.3914,
  },
  {
    name: "National Orthopaedic Hospital, Igbobi",
    address: "Ikorodu Road, Igbobi, Lagos",
    lga: "Somolu",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 450,
    operatingHours: "24/7",
    services: ["Orthopedics", "Trauma Surgery", "Physiotherapy", "Prosthetics"],
    latitude: 6.5333,
    longitude: 3.3667,
  },
  {
    name: "Federal Medical Centre, Ebute Metta",
    address: "Railway Compound, Ebute-Metta, Lagos",
    lga: "Lagos Mainland",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 300,
    operatingHours: "24/7",
    services: ["General Surgery", "Internal Medicine", "Pediatrics", "Obstetrics"],
    latitude: 6.4886,
    longitude: 3.3792,
  },
  {
    name: "Eko Hospital",
    address: "Mobolaji Bank Anthony Way, Ikeja, Lagos",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 130,
    operatingHours: "24/7",
    services: ["Radiotherapy", "General Medicine", "Surgery"],
    latitude: 6.5774,
    longitude: 3.3662,
  },
  {
    name: "First Consultants Medical Centre",
    address: "St. Gregory's College Road, Obalende, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 40,
    operatingHours: "24/7",
    services: ["General Practice", "Infectious Diseases", "Gynecology"],
    latitude: 6.4453,
    longitude: 3.4112,
  },
  {
    name: "Evercare Hospital Lekki",
    address: "Bisola Durosinmi Etti Dr, Lekki Phase 1, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 165,
    operatingHours: "24/7",
    services: ["Cardiology", "Neurology", "Orthopedics", "Critical Care"],
    latitude: 6.4474,
    longitude: 3.4731,
  },
  {
    name: "St. Ives Hospital",
    address: "12 Salvation Road, Opebi, Ikeja",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 45,
    operatingHours: "24/7",
    services: ["IVF", "Gynecology", "Obstetrics"],
    latitude: 6.5938,
    longitude: 3.3576,
  },
  {
    name: "Paelon Memorial Hospital",
    address: "1221 Ahmadu Bello Way, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 25,
    operatingHours: "24/7",
    services: ["Family Medicine", "Pediatrics", "Corporate Health"],
    latitude: 6.4253,
    longitude: 3.4211,
  },
  {
    name: "Nordica Fertility Centre",
    address: "106/108 Norman Williams Street, Ikoyi, Lagos",
    lga: "Ikoyi",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 15,
    operatingHours: "8am - 5pm",
    services: ["IVF", "Egg Freezing", "Andrology"],
    latitude: 6.4442,
    longitude: 3.4185,
  },
  {
    name: "Lagos Island General Hospital (Odan)",
    address: "1-3 Broad Street, Odan, Lagos",
    lga: "Lagos Island",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 250,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Maternity", "Eye Clinic"],
    latitude: 6.4539,
    longitude: 3.3903,
  },
  {
    name: "General Hospital, Ikeja",
    address: "349b Odusami Street, off Wemco Rd, Ogba, Ikeja",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 180,
    operatingHours: "24/7",
    services: ["General Medicine", "Surgery", "Pediatrics"],
    latitude: 6.6219,
    longitude: 3.3461,
  },
  {
    name: "General Hospital, Ikorodu",
    address: "TOS Benson Road, Ebute, Ikorodu",
    lga: "Ikorodu",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 150,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Emergency"],
    latitude: 6.6083,
    longitude: 3.4917,
  },
  {
    name: "General Hospital, Badagry",
    address: "Badagry, Lagos",
    lga: "Badagry",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 100,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity"],
    latitude: 6.4167,
    longitude: 2.8833,
  },
  {
    name: "General Hospital, Epe",
    address: "Epe, Lagos",
    lga: "Epe",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 120,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity"],
    latitude: 6.5833,
    longitude: 3.9833,
  },
  {
    name: "Alimosho General Hospital",
    address: "Lasu-Isheri Rd, Igando, Lagos",
    lga: "Alimosho",
    state: "Lagos",
    ownership: "Government",
    bedCapacity: 200,
    operatingHours: "24/7",
    services: ["General Medicine", "Maternity", "Pediatrics"],
    latitude: 6.5592,
    longitude: 3.2503,
  },
  {
    name: "Duchess International Hospital",
    address: "22A Joel Ogunnaike St, Ikeja GRA, Lagos",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 72,
    operatingHours: "24/7",
    services: ["Cardiology", "Surgery", "Wellness"],
    latitude: 6.5818,
    longitude: 3.3562,
  },
  {
    name: "Kelina Hospital",
    address: "7 Ologun Agbaje St, Victoria Island, Lagos",
    lga: "Eti-Osa",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 30,
    operatingHours: "24/7",
    services: ["Laser Surgery", "Urology", "Lithotripsy"],
    latitude: 6.4298,
    longitude: 3.4143,
  },
  {
    name: "The Bridge Clinic",
    address: "66 Oduduwa Way, Ikeja GRA, Lagos",
    lga: "Ikeja",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 10,
    operatingHours: "8am - 5pm",
    services: ["IVF", "Fertility Treatment"],
    latitude: 6.5764,
    longitude: 3.3567,
  },
  {
    name: "Eye Foundation Hospital",
    address: "50 Ogunlana Drive, Surulere, Lagos",
    lga: "Surulere",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 20,
    operatingHours: "24/7",
    services: ["Ophthalmology", "Eye Surgery", "Optometry"],
    latitude: 6.4938,
    longitude: 3.3558,
  },
  {
    name: "Lifebridge Specialist Hospital",
    address: "42 Montgomery Road, Sabo Yaba, Lagos",
    lga: "Yaba",
    state: "Lagos",
    ownership: "Private",
    bedCapacity: 35,
    operatingHours: "24/7",
    services: ["Cardiology", "Orthopedics", "General Surgery"],
    latitude: 6.5074,
    longitude: 3.3745,
  },
];

async function seed() {
  console.log("Seeding database with Lagos hospitals...");
  
  try {
    await db.insert(hospitals).values(lagosHospitals);
    console.log(`Successfully seeded ${lagosHospitals.length} hospitals`);
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
  
  process.exit(0);
}

seed();
