import { db } from "./db";
import { diagnosticCenters, diagnosticTests, physicians, physicianAffiliations, hospitals, generateDiagnosticCenterSlug, generatePhysicianSlug } from "@shared/schema";
import { eq } from "drizzle-orm";

const DIAGNOSTIC_CENTERS_DATA = [
  { name: "Pathcare Nigeria", description: "Full-service diagnostic laboratory offering comprehensive testing services with international quality standards.", address: "12 Adeola Odeku Street, Victoria Island", city: "Lagos", lga: "Eti-Osa", state: "Lagos", phone: "+234-1-2700000", email: "info@pathcare.ng", website: "https://pathcare.ng", operatingHours: "Mon-Fri: 7AM-6PM, Sat: 8AM-2PM", ownership: "Private", services: ["Blood Tests", "Urinalysis", "Imaging", "Histopathology", "Microbiology"], accreditations: ["CAP Accredited", "ISO 15189"], homeService: true, onlineResults: true, averageRating: 4.5, totalReviews: 120 },
  { name: "Medbury Medical Services", description: "Premium diagnostic center providing accurate and timely medical test results with state-of-the-art equipment.", address: "14 Norman Williams Street, Ikoyi", city: "Lagos", lga: "Eti-Osa", state: "Lagos", phone: "+234-1-2800000", email: "info@medbury.ng", website: "https://medbury.ng", operatingHours: "Mon-Sat: 7AM-7PM, Sun: 9AM-3PM", ownership: "Private", services: ["Radiology", "Laboratory", "Cardiac Diagnostics", "Ultrasound"], accreditations: ["ISO 15189"], homeService: true, onlineResults: true, averageRating: 4.3, totalReviews: 95 },
  { name: "Clina-Lancet Laboratories", description: "Pan-African diagnostic laboratory network with presence in Nigeria, offering world-class pathology services.", address: "7 Mobolaji Bank Anthony Way, Ikeja", city: "Lagos", lga: "Ikeja", state: "Lagos", phone: "+234-1-2900000", email: "lagos@clina-lancet.com", website: "https://clina-lancet.com", operatingHours: "Mon-Fri: 7AM-6PM, Sat: 8AM-1PM", ownership: "Private", services: ["Clinical Pathology", "Anatomical Pathology", "Genetics", "Drug Testing"], accreditations: ["SANAS Accredited", "ISO 15189"], homeService: false, onlineResults: true, averageRating: 4.6, totalReviews: 85 },
  { name: "Total Health Trust Diagnostic Centre", description: "Comprehensive diagnostic services backed by one of Nigeria's leading health maintenance organizations.", address: "25 Saka Tinubu Street, Victoria Island", city: "Lagos", lga: "Eti-Osa", state: "Lagos", phone: "+234-1-4600000", email: "diagnostics@totalhealth.ng", website: "https://totalhealth.ng", operatingHours: "Mon-Fri: 8AM-5PM, Sat: 9AM-2PM", ownership: "Private", services: ["Health Screening", "Laboratory", "Imaging", "ECG"], accreditations: ["NHIA Accredited"], homeService: false, onlineResults: true, averageRating: 4.0, totalReviews: 60 },
  { name: "Synlab Nigeria", description: "Part of the SYNLAB international network, offering advanced diagnostic testing with European quality standards.", address: "Plot 39 Ladoke Akintola Boulevard, Garki II", city: "Abuja", lga: "Garki", state: "FCT", phone: "+234-9-2910000", email: "abuja@synlab.ng", website: "https://synlab.ng", operatingHours: "Mon-Fri: 7AM-6PM, Sat: 8AM-2PM", ownership: "Private", services: ["Molecular Diagnostics", "Clinical Chemistry", "Hematology", "Microbiology", "Immunology"], accreditations: ["ISO 15189", "CAP Accredited"], homeService: true, onlineResults: true, averageRating: 4.7, totalReviews: 110 },
  { name: "Cedarcrest Hospitals Diagnostics", description: "Hospital-based diagnostic center with advanced imaging and laboratory services in Abuja.", address: "Apo District, Behind National Assembly Quarters", city: "Abuja", lga: "Apo", state: "FCT", phone: "+234-9-2920000", email: "diagnostics@cedarcresthospitals.com", operatingHours: "24/7 Emergency, Regular: Mon-Sat 7AM-7PM", ownership: "Private", services: ["CT Scan", "MRI", "Mammography", "Laboratory", "Ultrasound"], accreditations: ["JCI Accredited"], homeService: false, onlineResults: true, averageRating: 4.4, totalReviews: 75 },
  { name: "National Hospital Abuja Laboratory", description: "Government tertiary hospital diagnostic laboratory offering affordable comprehensive testing.", address: "Plot 132 Central District, Phase II", city: "Abuja", lga: "Municipal", state: "FCT", phone: "+234-9-4601000", operatingHours: "Mon-Fri: 8AM-4PM", ownership: "Government", services: ["Hematology", "Chemical Pathology", "Microbiology", "Histopathology", "Blood Bank"], accreditations: ["MLSCN Approved"], homeService: false, onlineResults: false, averageRating: 3.8, totalReviews: 45 },
  { name: "Mecure Healthcare Diagnostics", description: "Modern diagnostic center providing quick and reliable test results with patient-friendly service.", address: "5 Ademola Adetokunbo Crescent, Wuse 2", city: "Abuja", lga: "Wuse", state: "FCT", phone: "+234-9-2930000", email: "info@mecure.ng", operatingHours: "Mon-Sat: 7AM-6PM", ownership: "Private", services: ["Laboratory", "Radiology", "Ultrasound", "ECG", "Health Screening"], accreditations: ["ISO 15189"], homeService: true, onlineResults: true, averageRating: 4.2, totalReviews: 55 },
  { name: "University of Port Harcourt Teaching Hospital Lab", description: "Teaching hospital diagnostic laboratory with research capabilities and affordable testing.", address: "East-West Road, Choba", city: "Port Harcourt", lga: "Obio-Akpor", state: "Rivers", phone: "+234-84-230000", operatingHours: "Mon-Fri: 8AM-4PM, Sat: 8AM-12PM", ownership: "Government", services: ["Clinical Chemistry", "Hematology", "Medical Microbiology", "Virology", "Immunology"], accreditations: ["MDCN Accredited"], homeService: false, onlineResults: false, averageRating: 3.5, totalReviews: 30 },
  { name: "Genesis Diagnostics", description: "Patient-centered diagnostic laboratory in Port Harcourt offering fast and accurate results.", address: "23 Aba Road, GRA Phase 3", city: "Port Harcourt", lga: "Port Harcourt", state: "Rivers", phone: "+234-84-231000", email: "info@genesisdiagnostics.ng", operatingHours: "Mon-Sat: 7AM-6PM", ownership: "Private", services: ["Routine Blood Tests", "Hormonal Assays", "Infectious Disease Testing", "Urinalysis"], accreditations: ["MLSCN Approved"], homeService: true, onlineResults: true, averageRating: 4.1, totalReviews: 40 },
  { name: "Lifebridge Medical Diagnostics", description: "Specialized diagnostic center serving the south-south region with quality medical testing.", address: "45 Stadium Road, Port Harcourt", city: "Port Harcourt", lga: "Port Harcourt", state: "Rivers", phone: "+234-84-232000", email: "contact@lifebridge.ng", operatingHours: "Mon-Fri: 7AM-5PM, Sat: 8AM-2PM", ownership: "Private", services: ["Pathology", "Radiology", "Genetic Testing", "Allergy Testing"], accreditations: ["ISO 15189"], homeService: false, onlineResults: true, averageRating: 4.3, totalReviews: 35 },
  { name: "UCH Ibadan Diagnostic Centre", description: "Premier teaching hospital laboratory in western Nigeria with comprehensive diagnostic capabilities.", address: "Queen Elizabeth Road, Mokola", city: "Ibadan", lga: "Ibadan North", state: "Oyo", phone: "+234-2-2410000", operatingHours: "Mon-Fri: 8AM-4PM, Sat: 8AM-12PM", ownership: "Government", services: ["Clinical Pathology", "Histopathology", "Cytology", "Hematology", "Chemical Pathology"], accreditations: ["MDCN Accredited", "MLSCN Approved"], homeService: false, onlineResults: false, averageRating: 3.9, totalReviews: 50 },
  { name: "Biomedical Diagnostics Ibadan", description: "Private diagnostic laboratory offering affordable and reliable testing in Ibadan metropolis.", address: "15 Magazine Road, Jericho", city: "Ibadan", lga: "Ibadan North-West", state: "Oyo", phone: "+234-2-2420000", email: "info@biomeddiagnostics.ng", operatingHours: "Mon-Sat: 7AM-5PM", ownership: "Private", services: ["Blood Chemistry", "Serology", "Parasitology", "Pregnancy Tests", "STD Screening"], accreditations: ["MLSCN Approved"], homeService: true, onlineResults: true, averageRating: 4.0, totalReviews: 30 },
  { name: "Aminu Kano Teaching Hospital Laboratory", description: "Northern Nigeria's leading teaching hospital laboratory with comprehensive diagnostic testing.", address: "Zaria Road, Kano", city: "Kano", lga: "Tarauni", state: "Kano", phone: "+234-64-310000", operatingHours: "Mon-Fri: 8AM-4PM, Sat: 8AM-12PM", ownership: "Government", services: ["Hematology", "Chemical Pathology", "Microbiology", "Blood Banking", "Parasitology"], accreditations: ["MDCN Accredited"], homeService: false, onlineResults: false, averageRating: 3.7, totalReviews: 40 },
  { name: "Maitama District Hospital Diagnostics", description: "Government diagnostic facility providing accessible healthcare testing to Abuja residents.", address: "Aguiyi Ironsi Way, Maitama", city: "Abuja", lga: "Maitama", state: "FCT", phone: "+234-9-2940000", operatingHours: "Mon-Fri: 8AM-4PM", ownership: "Government", services: ["Basic Blood Tests", "Urinalysis", "Malaria RDT", "HIV Testing", "TB Screening"], accreditations: ["FMOH Approved"], homeService: false, onlineResults: false, averageRating: 3.4, totalReviews: 25 },
  { name: "Healthplus Diagnostics", description: "Modern diagnostic center offering comprehensive health screening packages in Lagos.", address: "Plot 3, Block A, Alausa CBD", city: "Lagos", lga: "Ikeja", state: "Lagos", phone: "+234-1-2950000", email: "info@healthplusdiag.ng", website: "https://healthplusdiag.ng", operatingHours: "Mon-Sat: 7AM-7PM", ownership: "Private", services: ["Executive Health Check", "Women's Health Panel", "Cardiac Risk Assessment", "Diabetes Screening"], accreditations: ["ISO 15189"], homeService: true, onlineResults: true, averageRating: 4.4, totalReviews: 65 },
  { name: "UNTH Enugu Diagnostic Services", description: "University of Nigeria Teaching Hospital diagnostic laboratory serving the southeast region.", address: "Ituku-Ozalla, Enugu", city: "Enugu", lga: "Enugu South", state: "Enugu", phone: "+234-42-250000", operatingHours: "Mon-Fri: 8AM-4PM, Sat: 8AM-12PM", ownership: "Government", services: ["Hematology", "Microbiology", "Chemical Pathology", "Histopathology", "Immunology"], accreditations: ["MDCN Accredited"], homeService: false, onlineResults: false, averageRating: 3.6, totalReviews: 35 },
  { name: "Diamond Diagnostics", description: "Quality-focused diagnostic center serving Enugu and the southeast with modern testing equipment.", address: "42 Ogui Road, Enugu", city: "Enugu", lga: "Enugu North", state: "Enugu", phone: "+234-42-251000", email: "info@diamonddiagnostics.ng", operatingHours: "Mon-Sat: 7AM-5PM", ownership: "Private", services: ["Laboratory Testing", "Ultrasound", "ECG", "X-Ray", "Health Screening"], accreditations: ["MLSCN Approved"], homeService: true, onlineResults: true, averageRating: 4.1, totalReviews: 25 },
  { name: "Mecure Healthcare Kano", description: "Northern Nigeria branch of Mecure Healthcare providing advanced diagnostic testing.", address: "15 Murtala Mohammed Way, Kano", city: "Kano", lga: "Nassarawa", state: "Kano", phone: "+234-64-320000", email: "kano@mecure.ng", operatingHours: "Mon-Sat: 7AM-5PM", ownership: "Private", services: ["Laboratory", "Imaging", "Health Screening", "Cardiac Testing"], accreditations: ["ISO 15189"], homeService: false, onlineResults: true, averageRating: 4.0, totalReviews: 20 },
  { name: "LASUTH Diagnostic Centre", description: "Lagos State University Teaching Hospital diagnostic services with advanced testing capabilities.", address: "1-5 Oba Akinjobi Way, Ikeja", city: "Lagos", lga: "Ikeja", state: "Lagos", phone: "+234-1-4700000", operatingHours: "Mon-Fri: 8AM-4PM, Sat: 8AM-1PM", ownership: "Government", services: ["Hematology", "Chemical Pathology", "Microbiology", "Molecular Diagnostics", "Cytogenetics"], accreditations: ["MDCN Accredited", "MLSCN Approved"], homeService: false, onlineResults: false, averageRating: 3.8, totalReviews: 55 },
  { name: "Lagoon Hospitals Diagnostics", description: "Premium hospital-based diagnostics with cutting-edge technology and same-day results for most tests.", address: "6 Turton Street, Lagos Island", city: "Lagos", lga: "Lagos Island", state: "Lagos", phone: "+234-1-4710000", email: "diagnostics@lagoonhospitals.com", website: "https://lagoonhospitals.com", operatingHours: "Mon-Sun: 7AM-9PM", ownership: "Private", services: ["MRI", "CT Scan", "PET Scan", "Mammography", "Laboratory", "Cardiac Imaging"], accreditations: ["JCI Accredited", "ISO 15189"], homeService: true, onlineResults: true, averageRating: 4.6, totalReviews: 90 },
  { name: "OAU Teaching Hospital Lab", description: "Obafemi Awolowo University Teaching Hospital diagnostic laboratory in Ile-Ife.", address: "Ilesa Road, Ile-Ife", city: "Ile-Ife", lga: "Ife Central", state: "Osun", phone: "+234-36-230000", operatingHours: "Mon-Fri: 8AM-4PM", ownership: "Government", services: ["Hematology", "Chemical Pathology", "Medical Microbiology", "Histopathology"], accreditations: ["MDCN Accredited"], homeService: false, onlineResults: false, averageRating: 3.5, totalReviews: 20 },
  { name: "Zankli Medical Centre Diagnostics", description: "Multi-specialty medical center with advanced diagnostic capabilities in Abuja.", address: "Plot 1021 Cadastral Zone, Jahi District", city: "Abuja", lga: "Jahi", state: "FCT", phone: "+234-9-2960000", email: "diagnostics@zankli.com", website: "https://zankli.com", operatingHours: "Mon-Sat: 7AM-7PM", ownership: "Private", services: ["MRI", "CT Scan", "Ultrasound", "Laboratory", "Endoscopy", "Cardiology Tests"], accreditations: ["SafeCare Level 4"], homeService: false, onlineResults: true, averageRating: 4.3, totalReviews: 50 },
  { name: "Kelina Hospital Diagnostics", description: "Quality diagnostic services at competitive prices in Abuja's Kubwa satellite town.", address: "Plot 82, Gado Nasko Way, Kubwa", city: "Abuja", lga: "Bwari", state: "FCT", phone: "+234-9-2970000", email: "info@kelina.ng", operatingHours: "Mon-Sat: 7AM-6PM", ownership: "Private", services: ["Laboratory", "Radiology", "Ultrasound", "ECG"], accreditations: ["MLSCN Approved"], homeService: true, onlineResults: true, averageRating: 4.1, totalReviews: 30 },
  { name: "Jos University Teaching Hospital Lab", description: "Diagnostic laboratory serving the middle belt region from Jos, Plateau State.", address: "Lamingo Road, Jos", city: "Jos", lga: "Jos North", state: "Plateau", phone: "+234-73-450000", operatingHours: "Mon-Fri: 8AM-4PM", ownership: "Government", services: ["Hematology", "Chemical Pathology", "Microbiology", "Blood Banking"], accreditations: ["MDCN Accredited"], homeService: false, onlineResults: false, averageRating: 3.4, totalReviews: 15 },
  { name: "UBTH Benin Diagnostic Centre", description: "University of Benin Teaching Hospital diagnostic services for Edo State and the south-south.", address: "PMB 1111, Ugbowo", city: "Benin City", lga: "Egor", state: "Edo", phone: "+234-52-600000", operatingHours: "Mon-Fri: 8AM-4PM, Sat: 8AM-12PM", ownership: "Government", services: ["Clinical Pathology", "Hematology", "Chemical Pathology", "Anatomical Pathology"], accreditations: ["MDCN Accredited"], homeService: false, onlineResults: false, averageRating: 3.6, totalReviews: 25 },
  { name: "Lily Hospitals Diagnostics", description: "Private hospital-based diagnostic center in Benin City with modern laboratory equipment.", address: "7 Sapele Road, Benin City", city: "Benin City", lga: "Oredo", state: "Edo", phone: "+234-52-601000", email: "diagnostics@lilyhospitals.com", operatingHours: "Mon-Sat: 7AM-6PM", ownership: "Private", services: ["Laboratory", "Radiology", "Ultrasound", "Mammography", "Cardiac Diagnostics"], accreditations: ["SafeCare Level 4", "ISO 15189"], homeService: true, onlineResults: true, averageRating: 4.4, totalReviews: 45 },
  { name: "FMC Abeokuta Diagnostic Lab", description: "Federal Medical Centre Abeokuta providing affordable diagnostic services.", address: "Idi-Aba, Abeokuta", city: "Abeokuta", lga: "Abeokuta South", state: "Ogun", phone: "+234-39-240000", operatingHours: "Mon-Fri: 8AM-4PM", ownership: "Government", services: ["Hematology", "Chemical Pathology", "Microbiology", "Histopathology"], accreditations: ["FMOH Approved"], homeService: false, onlineResults: false, averageRating: 3.3, totalReviews: 15 },
  { name: "Reddington Hospital Diagnostics", description: "Premium diagnostic services at one of Lagos's top private hospitals with rapid turnaround.", address: "12 Idowu Martins Street, Victoria Island", city: "Lagos", lga: "Eti-Osa", state: "Lagos", phone: "+234-1-4720000", email: "diagnostics@reddingtonhospital.com", website: "https://reddingtonhospital.com", operatingHours: "24/7", ownership: "Private", services: ["CT Scan", "MRI", "PET-CT", "Nuclear Medicine", "Advanced Laboratory", "Cardiac Catheterization"], accreditations: ["JCI Accredited", "ISO 15189", "CAP"], homeService: true, onlineResults: true, averageRating: 4.7, totalReviews: 100 },
  { name: "Nisa Premier Hospital Diagnostics", description: "Comprehensive diagnostic center in Abuja offering executive health checks and advanced imaging.", address: "Plot 1061, Cadastral Zone, Jabi", city: "Abuja", lga: "Jabi", state: "FCT", phone: "+234-9-2980000", email: "diagnostics@nisahospitals.com", operatingHours: "Mon-Sun: 7AM-8PM", ownership: "Private", services: ["MRI", "CT Scan", "Mammography", "Laboratory", "Endoscopy", "Colonoscopy"], accreditations: ["SafeCare Level 5"], homeService: false, onlineResults: true, averageRating: 4.5, totalReviews: 70 },
];

const DIAGNOSTIC_TESTS_DATA = [
  { testName: "Complete Blood Count (CBC)", category: "Hematology", description: "Measures red blood cells, white blood cells, hemoglobin, hematocrit, and platelets.", sampleType: "Blood", preparationNotes: "No special preparation needed. You may eat and drink normally.", turnaroundTime: "2-4 hours", priceMin: 3000, priceMax: 8000, insuranceAccepted: true, homeCollection: true },
  { testName: "Malaria Parasite Test", category: "Parasitology", description: "Detects the presence of malaria parasites in blood using microscopy or rapid diagnostic test.", sampleType: "Blood", preparationNotes: "No fasting required.", turnaroundTime: "1-2 hours", priceMin: 1500, priceMax: 5000, insuranceAccepted: true, homeCollection: true },
  { testName: "Liver Function Test (LFT)", category: "Clinical Chemistry", description: "Assesses liver health by measuring enzymes, proteins, and bilirubin in the blood.", sampleType: "Blood", preparationNotes: "Fasting for 8-12 hours is recommended.", turnaroundTime: "4-6 hours", priceMin: 5000, priceMax: 15000, insuranceAccepted: true, homeCollection: true },
  { testName: "Kidney Function Test (RFT)", category: "Clinical Chemistry", description: "Evaluates kidney function by measuring creatinine, BUN, electrolytes, and uric acid.", sampleType: "Blood", preparationNotes: "Fasting for 8-12 hours may be recommended.", turnaroundTime: "4-6 hours", priceMin: 5000, priceMax: 15000, insuranceAccepted: true, homeCollection: true },
  { testName: "Lipid Profile", category: "Clinical Chemistry", description: "Measures cholesterol levels including total cholesterol, HDL, LDL, and triglycerides.", sampleType: "Blood", preparationNotes: "Fast for 9-12 hours before the test. Drink only water.", turnaroundTime: "4-6 hours", priceMin: 5000, priceMax: 12000, insuranceAccepted: true, homeCollection: true },
  { testName: "Fasting Blood Sugar (FBS)", category: "Clinical Chemistry", description: "Measures blood glucose level after an overnight fast to screen for diabetes.", sampleType: "Blood", preparationNotes: "Fast for 8-12 hours. No food or drinks except water.", turnaroundTime: "1-2 hours", priceMin: 1500, priceMax: 5000, insuranceAccepted: true, homeCollection: true },
  { testName: "HbA1c (Glycated Hemoglobin)", category: "Clinical Chemistry", description: "Reflects average blood sugar levels over the past 2-3 months for diabetes monitoring.", sampleType: "Blood", preparationNotes: "No fasting required.", turnaroundTime: "4-8 hours", priceMin: 5000, priceMax: 15000, insuranceAccepted: true, homeCollection: true },
  { testName: "HIV 1 & 2 Screening", category: "Serology", description: "Tests for antibodies and antigens to detect HIV infection.", sampleType: "Blood", preparationNotes: "No special preparation needed. Counseling available.", turnaroundTime: "30 minutes - 2 hours", priceMin: 2000, priceMax: 8000, insuranceAccepted: true, homeCollection: false },
  { testName: "Hepatitis B Surface Antigen (HBsAg)", category: "Serology", description: "Screens for hepatitis B virus infection.", sampleType: "Blood", preparationNotes: "No special preparation needed.", turnaroundTime: "2-4 hours", priceMin: 2000, priceMax: 6000, insuranceAccepted: true, homeCollection: true },
  { testName: "Hepatitis C Antibody", category: "Serology", description: "Screens for hepatitis C virus infection by detecting antibodies.", sampleType: "Blood", preparationNotes: "No special preparation needed.", turnaroundTime: "2-4 hours", priceMin: 2500, priceMax: 8000, insuranceAccepted: true, homeCollection: true },
  { testName: "Thyroid Function Test (TFT)", category: "Endocrinology", description: "Measures TSH, T3, and T4 hormones to evaluate thyroid function.", sampleType: "Blood", preparationNotes: "Morning sample preferred. Some medications may need to be paused.", turnaroundTime: "6-24 hours", priceMin: 8000, priceMax: 25000, insuranceAccepted: true, homeCollection: true },
  { testName: "Pregnancy Test (Beta-hCG)", category: "Endocrinology", description: "Detects pregnancy by measuring human chorionic gonadotropin in blood.", sampleType: "Blood/Urine", preparationNotes: "First morning urine preferred for urine test.", turnaroundTime: "1-2 hours", priceMin: 1500, priceMax: 5000, insuranceAccepted: false, homeCollection: true },
  { testName: "Urinalysis", category: "Clinical Chemistry", description: "Analyzes urine for various substances including protein, glucose, blood, and bacteria.", sampleType: "Urine", preparationNotes: "Clean catch midstream urine sample required.", turnaroundTime: "1-2 hours", priceMin: 1500, priceMax: 4000, insuranceAccepted: true, homeCollection: true },
  { testName: "Widal Test", category: "Serology", description: "Tests for antibodies against Salmonella typhi to diagnose typhoid fever.", sampleType: "Blood", preparationNotes: "No special preparation needed.", turnaroundTime: "2-4 hours", priceMin: 2000, priceMax: 5000, insuranceAccepted: true, homeCollection: true },
  { testName: "Chest X-Ray", category: "Radiology", description: "Imaging of the chest to evaluate lungs, heart, and chest wall.", sampleType: "N/A", preparationNotes: "Remove all metal jewelry. Wear loose clothing.", turnaroundTime: "30 minutes - 1 hour", priceMin: 5000, priceMax: 15000, insuranceAccepted: true, homeCollection: false },
  { testName: "Abdominal Ultrasound", category: "Radiology", description: "Uses sound waves to image abdominal organs including liver, gallbladder, kidneys, and spleen.", sampleType: "N/A", preparationNotes: "Fast for 6-8 hours. Drink water 1 hour before to fill bladder.", turnaroundTime: "30 minutes - 1 hour", priceMin: 10000, priceMax: 25000, insuranceAccepted: true, homeCollection: false },
  { testName: "Pelvic Ultrasound", category: "Radiology", description: "Imaging of pelvic organs including uterus, ovaries, and bladder.", sampleType: "N/A", preparationNotes: "Drink 4-6 glasses of water 1 hour before scan. Do not empty bladder.", turnaroundTime: "30 minutes", priceMin: 10000, priceMax: 25000, insuranceAccepted: true, homeCollection: false },
  { testName: "Obstetric Ultrasound", category: "Radiology", description: "Monitors fetal development during pregnancy including growth, position, and anatomy.", sampleType: "N/A", preparationNotes: "Drink water 1 hour before for early pregnancy scans.", turnaroundTime: "30-45 minutes", priceMin: 10000, priceMax: 30000, insuranceAccepted: true, homeCollection: false },
  { testName: "MRI Scan (Brain)", category: "Advanced Imaging", description: "Detailed imaging of the brain to detect tumors, bleeding, infections, and structural abnormalities.", sampleType: "N/A", preparationNotes: "Remove all metal objects. Inform staff of any implants or pacemakers.", turnaroundTime: "1-2 hours (results 24-48 hours)", priceMin: 60000, priceMax: 150000, insuranceAccepted: true, homeCollection: false },
  { testName: "CT Scan (Chest/Abdomen)", category: "Advanced Imaging", description: "Cross-sectional imaging using X-rays to evaluate chest and abdominal organs in detail.", sampleType: "N/A", preparationNotes: "May require fasting. Contrast dye may be used - inform staff of allergies.", turnaroundTime: "1-2 hours (results 24-48 hours)", priceMin: 40000, priceMax: 120000, insuranceAccepted: true, homeCollection: false },
  { testName: "ECG (Electrocardiogram)", category: "Cardiac Diagnostics", description: "Records the electrical activity of the heart to detect rhythm abnormalities and heart conditions.", sampleType: "N/A", preparationNotes: "Avoid caffeine. Wear loose, comfortable clothing.", turnaroundTime: "15-30 minutes", priceMin: 3000, priceMax: 10000, insuranceAccepted: true, homeCollection: false },
  { testName: "Echocardiogram", category: "Cardiac Diagnostics", description: "Ultrasound of the heart showing chambers, valves, and blood flow patterns.", sampleType: "N/A", preparationNotes: "No special preparation needed.", turnaroundTime: "30-60 minutes", priceMin: 15000, priceMax: 45000, insuranceAccepted: true, homeCollection: false },
  { testName: "PSA (Prostate Specific Antigen)", category: "Tumor Markers", description: "Blood test to screen for prostate cancer and monitor prostate health in men.", sampleType: "Blood", preparationNotes: "Avoid ejaculation 48 hours before. No vigorous exercise.", turnaroundTime: "4-8 hours", priceMin: 5000, priceMax: 15000, insuranceAccepted: true, homeCollection: true },
  { testName: "Pap Smear (Cervical Screening)", category: "Cytology", description: "Screens for cervical cancer and precancerous changes in women.", sampleType: "Cervical cells", preparationNotes: "Avoid intercourse, douching, and vaginal medications 48 hours before.", turnaroundTime: "3-7 days", priceMin: 5000, priceMax: 15000, insuranceAccepted: true, homeCollection: false },
  { testName: "Mammography", category: "Radiology", description: "X-ray imaging of the breast to detect cancer, calcifications, and other abnormalities.", sampleType: "N/A", preparationNotes: "Schedule after menstrual period. No deodorant, powder, or cream on chest area.", turnaroundTime: "1-3 days", priceMin: 15000, priceMax: 40000, insuranceAccepted: true, homeCollection: false },
  { testName: "Genotype Test", category: "Hematology", description: "Determines hemoglobin genotype (AA, AS, SS, AC, SC) for sickle cell disease screening.", sampleType: "Blood", preparationNotes: "No special preparation needed.", turnaroundTime: "2-4 hours", priceMin: 2000, priceMax: 6000, insuranceAccepted: true, homeCollection: true },
  { testName: "Blood Group & Rhesus Factor", category: "Hematology", description: "Determines ABO blood group and Rh factor for transfusions and pregnancy management.", sampleType: "Blood", preparationNotes: "No special preparation needed.", turnaroundTime: "1-2 hours", priceMin: 1500, priceMax: 4000, insuranceAccepted: true, homeCollection: true },
  { testName: "Stool Analysis", category: "Parasitology", description: "Examines stool for parasites, blood, and other abnormalities.", sampleType: "Stool", preparationNotes: "Collect fresh sample in a clean container. Deliver within 2 hours.", turnaroundTime: "2-4 hours", priceMin: 2000, priceMax: 5000, insuranceAccepted: true, homeCollection: false },
  { testName: "Semen Analysis", category: "Reproductive Health", description: "Evaluates sperm count, motility, morphology, and other parameters for fertility assessment.", sampleType: "Semen", preparationNotes: "Abstain from ejaculation for 2-5 days before the test.", turnaroundTime: "4-8 hours", priceMin: 5000, priceMax: 15000, insuranceAccepted: false, homeCollection: false },
  { testName: "Culture and Sensitivity (Urine)", category: "Microbiology", description: "Identifies bacteria in urine and determines which antibiotics will be effective.", sampleType: "Urine", preparationNotes: "Clean catch midstream sample. Avoid antibiotics 48 hours before if possible.", turnaroundTime: "2-5 days", priceMin: 5000, priceMax: 12000, insuranceAccepted: true, homeCollection: true },
  { testName: "COVID-19 PCR Test", category: "Molecular Diagnostics", description: "Detects SARS-CoV-2 virus using polymerase chain reaction for active infection.", sampleType: "Nasopharyngeal swab", preparationNotes: "No food or drink 30 minutes before. Avoid nose blowing.", turnaroundTime: "12-48 hours", priceMin: 15000, priceMax: 50000, insuranceAccepted: true, homeCollection: true },
  { testName: "Vitamin D Level", category: "Clinical Chemistry", description: "Measures 25-hydroxyvitamin D to assess vitamin D status and bone health.", sampleType: "Blood", preparationNotes: "No special preparation needed.", turnaroundTime: "4-24 hours", priceMin: 8000, priceMax: 20000, insuranceAccepted: true, homeCollection: true },
  { testName: "Erythrocyte Sedimentation Rate (ESR)", category: "Hematology", description: "Measures how quickly red blood cells settle, indicating inflammation in the body.", sampleType: "Blood", preparationNotes: "No special preparation needed.", turnaroundTime: "1-2 hours", priceMin: 1500, priceMax: 4000, insuranceAccepted: true, homeCollection: true },
  { testName: "Fertility Hormone Panel (Female)", category: "Endocrinology", description: "Measures FSH, LH, prolactin, estradiol, and progesterone for fertility assessment.", sampleType: "Blood", preparationNotes: "Test on Day 2-5 of menstrual cycle. Morning sample preferred.", turnaroundTime: "24-48 hours", priceMin: 15000, priceMax: 40000, insuranceAccepted: true, homeCollection: true },
  { testName: "Full Executive Health Screening", category: "Health Screening", description: "Comprehensive health check including blood tests, imaging, cardiac assessment, and specialist consultation.", sampleType: "Multiple", preparationNotes: "Fast for 12 hours. Wear comfortable clothing. Allow 3-4 hours.", turnaroundTime: "24-48 hours", priceMin: 50000, priceMax: 250000, insuranceAccepted: true, homeCollection: false },
];

const PHYSICIANS_DATA = [
  { fullName: "Adebayo Oluwaseun", title: "Dr.", gender: "Male", specialty: "Cardiology", subspecialty: "Interventional Cardiology", qualifications: ["MBBS", "FWACP", "FMCP"], bio: "Board-certified cardiologist with over 15 years experience in interventional cardiology. Specializes in coronary stenting and cardiac catheterization.", yearsOfExperience: 15, consultationFee: 25000, phone: "+234-801-000-0001", languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Chidinma Okafor", title: "Dr.", gender: "Female", specialty: "Obstetrics & Gynecology", subspecialty: "Maternal-Fetal Medicine", qualifications: ["MBBS", "FWACS", "MPH"], bio: "Experienced OB/GYN specializing in high-risk pregnancies and maternal health. Passionate about reducing maternal mortality in Nigeria.", yearsOfExperience: 12, consultationFee: 20000, phone: "+234-802-000-0002", languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Mohammed Ibrahim", title: "Prof.", gender: "Male", specialty: "Internal Medicine", subspecialty: "Endocrinology", qualifications: ["MBBS", "FMCP", "PhD"], bio: "Professor of Medicine with expertise in diabetes management and endocrine disorders. Has published over 50 research papers.", yearsOfExperience: 25, consultationFee: 30000, languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: false, city: "Abuja", state: "FCT" },
  { fullName: "Funke Adeyemi", title: "Dr.", gender: "Female", specialty: "Pediatrics", subspecialty: "Neonatology", qualifications: ["MBBS", "FWACP", "DCH"], bio: "Dedicated pediatrician focusing on newborn care and childhood diseases. Experienced in managing premature infants.", yearsOfExperience: 10, consultationFee: 15000, phone: "+234-803-000-0004", languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Emeka Chukwuma", title: "Dr.", gender: "Male", specialty: "General Surgery", subspecialty: "Laparoscopic Surgery", qualifications: ["MBBS", "FWACS", "FACS"], bio: "Skilled surgeon specializing in minimally invasive laparoscopic procedures. Trained at Johns Hopkins University.", yearsOfExperience: 18, consultationFee: 25000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: false, city: "Enugu", state: "Enugu" },
  { fullName: "Aisha Bello", title: "Dr.", gender: "Female", specialty: "Dermatology", qualifications: ["MBBS", "FMCP"], bio: "Dermatologist treating skin conditions including eczema, acne, and skin cancer. Expert in skin care for all skin types.", yearsOfExperience: 8, consultationFee: 18000, phone: "+234-804-000-0006", languages: ["English", "Hausa", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Abuja", state: "FCT" },
  { fullName: "Olumide Fashola", title: "Dr.", gender: "Male", specialty: "Orthopedics", subspecialty: "Sports Medicine", qualifications: ["MBBS", "FWACS", "MSc Sports Med"], bio: "Orthopedic surgeon specializing in sports injuries, joint replacement, and trauma surgery.", yearsOfExperience: 14, consultationFee: 22000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: false, city: "Lagos", state: "Lagos" },
  { fullName: "Ngozi Eze", title: "Dr.", gender: "Female", specialty: "Ophthalmology", qualifications: ["MBBS", "FMCOph", "FICO"], bio: "Eye specialist experienced in cataract surgery, glaucoma management, and refractive surgery.", yearsOfExperience: 11, consultationFee: 15000, phone: "+234-805-000-0008", languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: true, city: "Port Harcourt", state: "Rivers" },
  { fullName: "Abdulrahman Musa", title: "Dr.", gender: "Male", specialty: "Psychiatry", qualifications: ["MBBS", "FMCPsych", "MPhil"], bio: "Psychiatrist specializing in depression, anxiety disorders, and substance abuse treatment in Nigeria.", yearsOfExperience: 9, consultationFee: 20000, languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: true, city: "Kano", state: "Kano" },
  { fullName: "Blessing Okonkwo", title: "Dr.", gender: "Female", specialty: "Radiology", subspecialty: "Interventional Radiology", qualifications: ["MBBS", "FMCR"], bio: "Diagnostic and interventional radiologist skilled in CT, MRI interpretation, and image-guided procedures.", yearsOfExperience: 7, consultationFee: 20000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: false, city: "Lagos", state: "Lagos" },
  { fullName: "Segun Alade", title: "Dr.", gender: "Male", specialty: "ENT (Ear, Nose & Throat)", qualifications: ["MBBS", "FWACS"], bio: "ENT specialist treating hearing disorders, sinus problems, and throat conditions. Experienced in head and neck surgery.", yearsOfExperience: 13, consultationFee: 18000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Ibadan", state: "Oyo" },
  { fullName: "Hauwa Aliyu", title: "Dr.", gender: "Female", specialty: "Family Medicine", qualifications: ["MBBS", "FWACP(FM)"], bio: "Family medicine physician providing comprehensive primary healthcare for all ages. Focused on preventive medicine.", yearsOfExperience: 6, consultationFee: 10000, phone: "+234-806-000-0012", languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: true, city: "Abuja", state: "FCT" },
  { fullName: "Chinedu Nwosu", title: "Dr.", gender: "Male", specialty: "Urology", qualifications: ["MBBS", "FWACS"], bio: "Urologist specializing in prostate diseases, kidney stones, and male infertility treatments.", yearsOfExperience: 16, consultationFee: 22000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: false, city: "Lagos", state: "Lagos" },
  { fullName: "Yetunde Bakare", title: "Dr.", gender: "Female", specialty: "Anesthesiology", qualifications: ["MBBS", "FMCA", "DA"], bio: "Anesthesiologist experienced in general and regional anesthesia for all types of surgical procedures.", yearsOfExperience: 10, consultationFee: 15000, languages: ["English", "Yoruba"], acceptingNewPatients: false, teleconsultation: false, city: "Lagos", state: "Lagos" },
  { fullName: "Osagie Ehizogie", title: "Dr.", gender: "Male", specialty: "Neurology", qualifications: ["MBBS", "FMCP(Neuro)"], bio: "Neurologist treating stroke, epilepsy, headaches, and neurodegenerative diseases.", yearsOfExperience: 12, consultationFee: 25000, languages: ["English", "Edo"], acceptingNewPatients: true, teleconsultation: true, city: "Benin City", state: "Edo" },
  { fullName: "Fatima Sani", title: "Dr.", gender: "Female", specialty: "Pediatrics", subspecialty: "Pediatric Cardiology", qualifications: ["MBBS", "FWACP", "MSc Paed Cardio"], bio: "Pediatric cardiologist managing congenital and acquired heart diseases in children.", yearsOfExperience: 8, consultationFee: 20000, languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: true, city: "Kano", state: "Kano" },
  { fullName: "Tunde Ogunleye", title: "Dr.", gender: "Male", specialty: "Gastroenterology", qualifications: ["MBBS", "FMCP", "MSc GI"], bio: "Gastroenterologist specializing in liver diseases, endoscopy procedures, and digestive disorders common in Nigeria.", yearsOfExperience: 11, consultationFee: 22000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Grace Akpan", title: "Dr.", gender: "Female", specialty: "Nephrology", qualifications: ["MBBS", "FMCP(Neph)"], bio: "Nephrologist specializing in kidney diseases, dialysis management, and kidney transplant care.", yearsOfExperience: 9, consultationFee: 20000, languages: ["English", "Efik", "Ibibio"], acceptingNewPatients: true, teleconsultation: true, city: "Uyo", state: "Akwa Ibom" },
  { fullName: "Kabir Danjuma", title: "Dr.", gender: "Male", specialty: "Pulmonology", qualifications: ["MBBS", "FMCP(Pulm)"], bio: "Pulmonologist treating asthma, COPD, tuberculosis, and other respiratory conditions.", yearsOfExperience: 10, consultationFee: 18000, languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: true, city: "Jos", state: "Plateau" },
  { fullName: "Ifeoma Nnamdi", title: "Dr.", gender: "Female", specialty: "Oncology", subspecialty: "Medical Oncology", qualifications: ["MBBS", "FMCP", "MSc Oncology"], bio: "Medical oncologist experienced in treating breast, cervical, and prostate cancers with chemotherapy and targeted therapies.", yearsOfExperience: 13, consultationFee: 30000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Oluwole Adewale", title: "Prof.", gender: "Male", specialty: "Neurosurgery", qualifications: ["MBBS", "FWACS(Neurosurg)", "PhD"], bio: "Professor of Neurosurgery with expertise in brain tumor surgery, spinal surgery, and neurotrauma.", yearsOfExperience: 22, consultationFee: 40000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: false, city: "Ibadan", state: "Oyo" },
  { fullName: "Amina Yusuf", title: "Dr.", gender: "Female", specialty: "Rheumatology", qualifications: ["MBBS", "FMCP(Rheum)"], bio: "Rheumatologist treating arthritis, lupus, and other autoimmune conditions.", yearsOfExperience: 7, consultationFee: 18000, languages: ["English", "Hausa", "Fulani"], acceptingNewPatients: true, teleconsultation: true, city: "Abuja", state: "FCT" },
  { fullName: "Obi Okwuosa", title: "Dr.", gender: "Male", specialty: "Cardiothoracic Surgery", qualifications: ["MBBS", "FWACS(CTS)"], bio: "Cardiothoracic surgeon performing open heart surgery, valve replacements, and coronary bypass surgery.", yearsOfExperience: 17, consultationFee: 35000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: false, city: "Lagos", state: "Lagos" },
  { fullName: "Folashade Oyelaran", title: "Dr.", gender: "Female", specialty: "Hematology", qualifications: ["MBBS", "FMCPath(Haem)"], bio: "Hematologist specializing in sickle cell disease, blood cancers, and bleeding disorders.", yearsOfExperience: 10, consultationFee: 20000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Bashir Mohammed", title: "Dr.", gender: "Male", specialty: "Emergency Medicine", qualifications: ["MBBS", "FWACP(EM)"], bio: "Emergency medicine specialist with experience in trauma management and critical care.", yearsOfExperience: 8, consultationFee: 15000, languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: false, city: "Abuja", state: "FCT" },
  { fullName: "Nkechi Ogbuagu", title: "Dr.", gender: "Female", specialty: "Infectious Diseases", qualifications: ["MBBS", "FMCP", "MSc Inf Dis"], bio: "Infectious disease specialist with expertise in HIV/AIDS, tuberculosis, and tropical diseases.", yearsOfExperience: 11, consultationFee: 18000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: true, city: "Enugu", state: "Enugu" },
  { fullName: "Damilola Ogunbiyi", title: "Dr.", gender: "Male", specialty: "Plastic Surgery", subspecialty: "Reconstructive Surgery", qualifications: ["MBBS", "FWACS(Plastic)"], bio: "Plastic and reconstructive surgeon specializing in burn management, cleft lip repair, and cosmetic procedures.", yearsOfExperience: 9, consultationFee: 30000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Stella Edet", title: "Dr.", gender: "Female", specialty: "Pathology", subspecialty: "Anatomical Pathology", qualifications: ["MBBS", "FMCPath"], bio: "Anatomical pathologist specializing in surgical pathology and cytopathology diagnostics.", yearsOfExperience: 12, consultationFee: 15000, languages: ["English", "Efik"], acceptingNewPatients: false, teleconsultation: false, city: "Calabar", state: "Cross River" },
  { fullName: "Adamu Garba", title: "Dr.", gender: "Male", specialty: "Cardiology", subspecialty: "Electrophysiology", qualifications: ["MBBS", "FMCP", "FRCP"], bio: "Cardiologist with sub-specialization in cardiac electrophysiology and pacemaker implantation.", yearsOfExperience: 14, consultationFee: 28000, languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: true, city: "Abuja", state: "FCT" },
  { fullName: "Nneka Obi", title: "Dr.", gender: "Female", specialty: "Obstetrics & Gynecology", subspecialty: "Reproductive Endocrinology", qualifications: ["MBBS", "FWACS", "MSc Reprod Med"], bio: "Fertility specialist helping couples overcome infertility through IVF and assisted reproductive technologies.", yearsOfExperience: 10, consultationFee: 25000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Yinka Oladipo", title: "Dr.", gender: "Male", specialty: "Pediatrics", subspecialty: "Pediatric Neurology", qualifications: ["MBBS", "FWACP", "MSc Paed Neuro"], bio: "Pediatric neurologist treating epilepsy, developmental delays, and neurological conditions in children.", yearsOfExperience: 9, consultationFee: 20000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Ibadan", state: "Oyo" },
  { fullName: "Halima Abubakar", title: "Dr.", gender: "Female", specialty: "Internal Medicine", subspecialty: "Hepatology", qualifications: ["MBBS", "FMCP"], bio: "Internist specializing in liver diseases including hepatitis B/C management common in Nigeria.", yearsOfExperience: 8, consultationFee: 18000, languages: ["English", "Hausa", "Kanuri"], acceptingNewPatients: true, teleconsultation: true, city: "Maiduguri", state: "Borno" },
  { fullName: "Oluwafemi Adeniyi", title: "Dr.", gender: "Male", specialty: "General Surgery", subspecialty: "Hepatobiliary Surgery", qualifications: ["MBBS", "FWACS"], bio: "General surgeon with expertise in liver, gallbladder, and pancreatic surgeries.", yearsOfExperience: 16, consultationFee: 25000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: false, city: "Lagos", state: "Lagos" },
  { fullName: "Amaka Onyema", title: "Dr.", gender: "Female", specialty: "Dentistry", subspecialty: "Orthodontics", qualifications: ["BDS", "FMCDS(Ortho)"], bio: "Orthodontist specializing in braces, aligners, and jaw correction procedures.", yearsOfExperience: 7, consultationFee: 15000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: true, city: "Owerri", state: "Imo" },
  { fullName: "Babatunde Kolawole", title: "Prof.", gender: "Male", specialty: "Obstetrics & Gynecology", subspecialty: "Gynecological Oncology", qualifications: ["MBBS", "FWACS", "PhD"], bio: "Professor of Gynecological Oncology specializing in cervical and ovarian cancer treatment.", yearsOfExperience: 20, consultationFee: 35000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: false, city: "Lagos", state: "Lagos" },
  { fullName: "Sadiq Shehu", title: "Dr.", gender: "Male", specialty: "Orthopedics", subspecialty: "Spine Surgery", qualifications: ["MBBS", "FWACS(Ortho)"], bio: "Orthopedic spine surgeon treating back pain, disc herniations, and spinal deformities.", yearsOfExperience: 12, consultationFee: 25000, languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: false, city: "Kano", state: "Kano" },
  { fullName: "Victoria Effiong", title: "Dr.", gender: "Female", specialty: "Family Medicine", qualifications: ["MBBS", "FWACP(FM)", "MPH"], bio: "Family physician focused on community health and chronic disease management in underserved areas.", yearsOfExperience: 6, consultationFee: 8000, languages: ["English", "Efik", "Ibibio"], acceptingNewPatients: true, teleconsultation: true, city: "Uyo", state: "Akwa Ibom" },
  { fullName: "Chukwudi Okafor", title: "Dr.", gender: "Male", specialty: "Radiology", subspecialty: "Neuroradiology", qualifications: ["MBBS", "FMCR", "MSc NeuroRad"], bio: "Neuroradiologist specializing in brain and spine imaging using CT and MRI.", yearsOfExperience: 10, consultationFee: 20000, languages: ["English", "Igbo"], acceptingNewPatients: true, teleconsultation: false, city: "Enugu", state: "Enugu" },
  { fullName: "Lola Akinwumi", title: "Dr.", gender: "Female", specialty: "Dermatology", subspecialty: "Cosmetic Dermatology", qualifications: ["MBBS", "FMCP(Derm)"], bio: "Dermatologist specializing in cosmetic procedures, skin rejuvenation, and treatment of pigmentation disorders.", yearsOfExperience: 8, consultationFee: 20000, languages: ["English", "Yoruba"], acceptingNewPatients: true, teleconsultation: true, city: "Lagos", state: "Lagos" },
  { fullName: "Usman Bala", title: "Dr.", gender: "Male", specialty: "Nephrology", qualifications: ["MBBS", "FMCP(Neph)"], bio: "Nephrologist managing chronic kidney disease, dialysis patients, and kidney transplant evaluations.", yearsOfExperience: 11, consultationFee: 22000, languages: ["English", "Hausa"], acceptingNewPatients: true, teleconsultation: true, city: "Abuja", state: "FCT" },
];

export async function seedDiagnosticCentersAndPhysicians() {
  console.log("Seeding diagnostic centers...");
  
  const existingCenters = await db.select({ id: diagnosticCenters.id }).from(diagnosticCenters);
  if (existingCenters.length > 0) {
    console.log("Diagnostic centers already seeded, skipping...");
  } else {
    for (const centerData of DIAGNOSTIC_CENTERS_DATA) {
      const [center] = await db.insert(diagnosticCenters).values({
        ...centerData,
        slug: generateDiagnosticCenterSlug(centerData.name),
      }).returning();
      
      const testsForCenter = DIAGNOSTIC_TESTS_DATA.slice(0, Math.floor(Math.random() * 15) + 10);
      for (const testData of testsForCenter) {
        const priceFactor = centerData.ownership === "Government" ? 0.6 : (centerData.accreditations.some(a => a.includes("JCI")) ? 1.3 : 1.0);
        await db.insert(diagnosticTests).values({
          centerId: center.id,
          ...testData,
          priceMin: Math.round((testData.priceMin || 0) * priceFactor),
          priceMax: Math.round((testData.priceMax || 0) * priceFactor),
          homeCollection: centerData.homeService ? testData.homeCollection : false,
        });
      }
    }
    console.log(`Seeded ${DIAGNOSTIC_CENTERS_DATA.length} diagnostic centers with tests.`);
  }

  console.log("Seeding physicians...");
  const existingPhysicians = await db.select({ id: physicians.id }).from(physicians);
  if (existingPhysicians.length > 0) {
    console.log("Physicians already seeded, skipping...");
  } else {
    const allHospitals = await db.select({ id: hospitals.id, state: hospitals.state, city: hospitals.city }).from(hospitals);
    
    for (const physicianData of PHYSICIANS_DATA) {
      const [physician] = await db.insert(physicians).values({
        ...physicianData,
        slug: generatePhysicianSlug(physicianData.fullName),
      }).returning();
      
      const stateHospitals = allHospitals.filter(h => h.state === physicianData.state);
      const affiliateHospitals = stateHospitals.length > 0 
        ? stateHospitals.slice(0, Math.floor(Math.random() * 3) + 1) 
        : allHospitals.slice(0, 1);
      
      const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
      for (const hospital of affiliateHospitals) {
        const selectedDays = days.slice(0, Math.floor(Math.random() * 3) + 2);
        await db.insert(physicianAffiliations).values({
          physicianId: physician.id,
          hospitalId: hospital.id,
          role: physicianData.yearsOfExperience > 15 ? "Senior Consultant" : "Consultant",
          department: physicianData.specialty,
          availableDays: selectedDays,
          availableHours: "9:00 AM - 4:00 PM",
        });
      }
    }
    console.log(`Seeded ${PHYSICIANS_DATA.length} physicians with hospital affiliations.`);
  }
}
