// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carenaija-home/Desktop.tsx": () => import("../components/mockups/carenaija-home/Desktop.tsx"),
  "./components/mockups/carenaija-home/Mobile.tsx": () => import("../components/mockups/carenaija-home/Mobile.tsx"),
  "./components/mockups/carenaija-hospital/Desktop.tsx": () => import("../components/mockups/carenaija-hospital/Desktop.tsx"),
  "./components/mockups/carenaija-hospital/Mobile.tsx": () => import("../components/mockups/carenaija-hospital/Mobile.tsx"),
  "./components/mockups/carenaija-search/Desktop.tsx": () => import("../components/mockups/carenaija-search/Desktop.tsx"),
  "./components/mockups/carenaija-search/Mobile.tsx": () => import("../components/mockups/carenaija-search/Mobile.tsx")
};
